# Generated by Django 6.0 on 2026-03-27 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_staff_to_userattribute(apps, schema_editor):
    Staff = apps.get_model("rental_shop", "Staff")
    UserAttribute = apps.get_model("rental_shop", "UserAttribute")
    User = apps.get_model("auth", "User")

    # yoshi ユーザを取得 (id=1) または先頭のユーザを取得
    yoshi = User.objects.filter(pk=1).first() or User.objects.first()
    if not yoshi:
        return

    for staff in Staff.objects.all():
        UserAttribute.objects.get_or_create(
            id=staff.id,
            defaults={
                "user": yoshi,
                "role": "staff",
                "nickname": staff.name,
                "description": staff.description,
                "image": staff.image,
                "created_at": staff.created_at,
                "updated_at": staff.updated_at,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("rental_shop", "0002_cart_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("staff", "店舗スタッフ"), ("customer", "一般購入者")],
                        default="staff",
                        max_length=20,
                        verbose_name="ロール",
                    ),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="表示名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="自己紹介"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="rental_shop/staff",
                        verbose_name="プロフィール画像",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザ",
                    ),
                ),
                (
                    "warehouses",
                    models.ManyToManyField(
                        through="rental_shop.WarehouseStaff", to="rental_shop.warehouse"
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_staff_to_userattribute),
        migrations.AlterField(
            model_name="cart",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rental_shop.userattribute",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rental_shop.userattribute",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rental_shop.userattribute",
            ),
        ),
        migrations.AlterField(
            model_name="warehousestaff",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rental_shop.userattribute",
            ),
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
