# Generated by Django 6.0 on 2026-03-27 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rental_shop",
            "0003_userattribute_alter_cart_staff_alter_invoice_staff_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="rental_end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="rental_start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
