from django.urls import path

from taxonomy.views import (
    BreedDeleteView,
    BreedDetailView,
    BreedListView,
    BreedUpdateView,
    IndexView,
    LLMTaxonomyCandidateApproveView,
    LLMTaxonomyCandidateBulkApproveView,
    LLMTaxonomyCandidateBulkRejectView,
    LLMTaxonomyCandidateCreateView,
    LLMTaxonomyCandidateGenerationJobStepView,
    LLMTaxonomyCandidateListView,
    LLMTaxonomyCandidateRejectView,
    KingdomCreateView,
    PhylumCreateView,
    ClassificationCreateView,
    FamilyCreateView,
    GenusCreateView,
    SpeciesCreateView,
    BreedCreateView,
    TagCreateView,
    BreedTagUpdateView,
    ObservationView,
    TaxonomyBreedCreateView,
)

app_name = "txo"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("breeds/", BreedListView.as_view(), name="breed_list"),
    path("breeds/new/", TaxonomyBreedCreateView.as_view(), name="breed_new"),
    path(
        "llm-candidates/",
        LLMTaxonomyCandidateListView.as_view(),
        name="llm_candidate_list",
    ),
    path(
        "llm-candidates/new/",
        LLMTaxonomyCandidateCreateView.as_view(),
        name="llm_candidate_new",
    ),
    path(
        "llm-candidates/jobs/<int:pk>/step/",
        LLMTaxonomyCandidateGenerationJobStepView.as_view(),
        name="llm_candidate_generation_job_step",
    ),
    path(
        "llm-candidates/<int:pk>/approve/",
        LLMTaxonomyCandidateApproveView.as_view(),
        name="llm_candidate_approve",
    ),
    path(
        "llm-candidates/approve-all/",
        LLMTaxonomyCandidateBulkApproveView.as_view(),
        name="llm_candidate_approve_all",
    ),
    path(
        "llm-candidates/reject-all/",
        LLMTaxonomyCandidateBulkRejectView.as_view(),
        name="llm_candidate_reject_all",
    ),
    path(
        "llm-candidates/<int:pk>/reject/",
        LLMTaxonomyCandidateRejectView.as_view(),
        name="llm_candidate_reject",
    ),
    path("breeds/<int:pk>/", BreedDetailView.as_view(), name="breed_detail"),
    path("breeds/<int:pk>/edit/", BreedUpdateView.as_view(), name="breed_edit"),
    path("breeds/<int:pk>/delete/", BreedDeleteView.as_view(), name="breed_delete"),
    path("kingdom/create/", KingdomCreateView.as_view(), name="kingdom_create"),
    path("phylum/create/", PhylumCreateView.as_view(), name="phylum_create"),
    path(
        "classification/create/",
        ClassificationCreateView.as_view(),
        name="classification_create",
    ),
    path("family/create/", FamilyCreateView.as_view(), name="family_create"),
    path("genus/create/", GenusCreateView.as_view(), name="genus_create"),
    path("species/create/", SpeciesCreateView.as_view(), name="species_create"),
    path("breed/create/", BreedCreateView.as_view(), name="breed_create"),
    path("tag/create/", TagCreateView.as_view(), name="tag_create"),
    path("breed_tag/update/", BreedTagUpdateView.as_view(), name="breed_tags_update"),
    path("observation/", ObservationView.as_view(), name="observation"),
]
