from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = "soil"
urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("company/create", views.CompanyCreateView.as_view(), name="company_create"),
    path(
        "company/<int:pk>/detail",
        views.CompanyDetailView.as_view(),
        name="company_detail",
    ),
    path(
        "company/<int:company_id>/land/create",
        views.LandCreateView.as_view(),
        name="land_create",
    ),
    path("prefectures/", views.PrefecturesView.as_view(), name="prefectures"),
    path(
        "prefecture/<int:prefecture_id>/cities",
        views.PrefectureCitiesView.as_view(),
        name="prefecture_cities",
    ),
    path(
        "prefecture/<int:prefecture_id>/detail",
        views.PrefectureDetailView.as_view(),
        name="prefecture_detail",
    ),
    path(
        "company/<int:company_id>/land/<int:pk>/detail",
        views.LandDetailView.as_view(),
        name="land_detail",
    ),
    path(
        "company/<int:company_id>/land_ledger/<int:land_ledger_id>/standard_report",
        views.StandardReportView.as_view(),
        name="standard_report",
    ),
    path(
        "hardness/upload",
        views.HardnessUploadView.as_view(),
        name="hardness_upload",
    ),
    path(
        "chemical/upload",
        views.ChemicalUploadView.as_view(),
        name="chemical_upload",
    ),
    path(
        "chemical/success",
        views.ChemicalUploadSuccessView.as_view(),
        name="chemical_success",
    ),
    path(
        "chemical/association",
        views.ChemicalAssociationView.as_view(),
        name="chemical_association",
    ),
    path(
        "chemical/association/field_row/<int:row_index>",
        views.ChemicalAssociationRowView.as_view(),
        name="chemical_association_field_row",
    ),
    path(
        "chemical/association/success",
        views.ChemicalSuccessView.as_view(),
        name="chemical_association_success",
    ),
    path(
        "chemical/download_sample/",
        views.ChemicalDownloadSampleView.as_view(),
        name="chemical_download_sample",
    ),
    path(
        "chemical/delete_all/",
        views.ChemicalDeleteAllView.as_view(),
        name="chemical_delete_all",
    ),
    path(
        "hardness/delete_all",
        views.HardnessDeleteAllView.as_view(),
        name="hardness_delete_all",
    ),
    path(
        "hardness/generate_csv",
        views.HardnessGenerateDummyCsvView.as_view(),
        name="hardness_generate_dummy_csv",
    ),
    path(
        "hardness/success",
        views.HardnessSuccessView.as_view(),
        name="hardness_success",
    ),
    path(
        "hardness/association",
        views.HardnessAssociationView.as_view(),
        name="hardness_association",
    ),
    path(
        "hardness/association/field_group/<int:memory_anchor>",
        views.HardnessAssociationFieldGroupView.as_view(),
        name="hardness_association_field_group",
    ),
    path(
        "hardness/association/success",
        views.HardnessAssociationSuccessView.as_view(),
        name="hardness_association_success",
    ),
    path(
        "route_suggest/upload",
        views.RouteSuggestUploadView.as_view(),
        name="route_suggest_upload",
    ),
    path(
        "route_suggest/ordering",
        views.RouteSuggestOrderingView.as_view(),
        name="route_suggest_ordering",
    ),
    path(
        "route_suggest/success",
        views.RouteSuggestSuccessView.as_view(),
        name="route_suggest_success",
    ),
    path(
        "picture/land/associate",
        views.AssociatePictureAndLandView.as_view(),
        name="associate_picture_and_land",
    ),
    path(
        "picture/land/associate/result",
        views.AssociatePictureAndLandResultView.as_view(),
        name="associate_picture_and_land_result",
    ),
    path(
        "rokunohe/land-registry",
        views.RokunoheLandRegistryListView.as_view(),
        name="rokunohe_land_registry",
    ),
    path(
        "land-ledger/create-ajax/",
        views.LandLedgerCreateAjaxView.as_view(),
        name="land_ledger_create_ajax",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
