# Generated by Django 6.0 on 2026-01-19 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="銀行名"
                    ),
                ),
                (
                    "financial_code",
                    models.CharField(max_length=10, verbose_name="金融機関コード"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="備考"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "銀行マスタ",
                "verbose_name_plural": "銀行マスタ",
                "db_table": "bank",
            },
        ),
        migrations.CreateModel(
            name="MufgDepositCsvRaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField(verbose_name="日付")),
                ("summary", models.CharField(max_length=255, verbose_name="摘要")),
                (
                    "summary_detail",
                    models.CharField(max_length=255, verbose_name="摘要内容"),
                ),
                (
                    "payment_amount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="支払い金額"
                    ),
                ),
                (
                    "deposit_amount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="預かり金額"
                    ),
                ),
                ("balance", models.IntegerField(verbose_name="差引残高")),
                (
                    "memo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="メモ"
                    ),
                ),
                (
                    "uncollected_flag",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="未資金化区分",
                    ),
                ),
                (
                    "inout_type",
                    models.CharField(max_length=10, verbose_name="入払区分"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="bank.bank"
                    ),
                ),
            ],
            options={
                "verbose_name": "MUFG普通預金CSV Raw",
                "verbose_name_plural": "MUFG普通預金CSV Raw",
                "db_table": "mufg_deposit_csv_raw",
            },
        ),
    ]
