# Generated by Django 6.0 on 2026-01-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_mufgdepositcsvraw_unique_mufg_deposit_csv_raw"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mufgdepositcsvraw",
            name="unique_mufg_deposit_csv_raw",
        ),
        migrations.AddConstraint(
            model_name="mufgdepositcsvraw",
            constraint=models.UniqueConstraint(
                fields=(
                    "bank",
                    "trade_date",
                    "summary",
                    "summary_detail",
                    "balance",
                    "inout_type",
                ),
                name="unique_mufg_deposit_csv_raw",
            ),
        ),
    ]
