# Generated by Django 6.0 on 2026-01-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_remove_mufgdepositcsvraw_unique_mufg_deposit_csv_raw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mufgdepositcsvraw",
            name="inout_type",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="入払区分"
            ),
        ),
    ]
