# Generated by Django 6.0 on 2026-01-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_alter_mufgdepositcsvraw_inout_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="account_number",
            field=models.CharField(
                blank=True, max_length=7, null=True, verbose_name="口座番号"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="branch_code",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="店番"
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=100, verbose_name="銀行名"),
        ),
        migrations.AddConstraint(
            model_name="bank",
            constraint=models.UniqueConstraint(
                fields=("financial_code", "branch_code", "account_number"),
                name="unique_bank_account",
            ),
        ),
    ]
