# Generated by Django 6.0 on 2026-01-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_bank_account_number_bank_branch_code_alter_bank_name_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="bank",
            table=None,
        ),
        migrations.AlterModelTable(
            name="mufgdepositcsvraw",
            table=None,
        ),
    ]
