# Generated by Django 6.0 on 2026-01-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0006_alter_bank_table_alter_mufgdepositcsvraw_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mufgdepositcsvraw",
            name="unique_mufg_deposit_csv_raw",
        ),
        migrations.AddConstraint(
            model_name="mufgdepositcsvraw",
            constraint=models.UniqueConstraint(
                fields=(
                    "bank",
                    "trade_date",
                    "summary",
                    "summary_detail",
                    "payment_amount",
                    "deposit_amount",
                    "balance",
                    "inout_type",
                ),
                name="unique_mufg_deposit_csv_raw",
            ),
        ),
    ]
