# Generated by Django 6.0 on 2026-01-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0007_remove_mufgdepositcsvraw_unique_mufg_deposit_csv_raw_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositSummaryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="カテゴリ名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="表示順"),
                ),
            ],
            options={
                "verbose_name": "摘要カテゴリマスタ",
                "verbose_name_plural": "摘要カテゴリマスタ",
            },
        ),
        migrations.CreateModel(
            name="DepositSummaryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="摘要（CSV表記）"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, null=True, verbose_name="説明文（公式）"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bank.depositsummarycategory",
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
            options={
                "verbose_name": "摘要マスタ",
                "verbose_name_plural": "摘要マスタ",
            },
        ),
    ]
