# Generated by Django 6.0 on 2026-01-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0008_depositsummarycategory_depositsummarymaster"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE bank_depositsummarymaster MODIFY summary VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;",
            reverse_sql="ALTER TABLE bank_depositsummarymaster MODIFY summary VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL;",
        ),
    ]
