# Generated by Django 5.1 on 2024-09-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "taxonomy_m_classification",
            },
        ),
        migrations.CreateModel(
            name="Kingdom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "taxonomy_m_kingdom",
            },
        ),
        migrations.CreateModel(
            name="NaturalMonument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "taxonomy_m_natural_monument",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("remark", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "taxonomy_m_tag",
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255, null=True)),
                (
                    "classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomy.classification",
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_m_family",
            },
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomy.family",
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_m_genus",
            },
        ),
        migrations.CreateModel(
            name="Phylum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255, null=True)),
                (
                    "kingdom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomy.kingdom",
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_m_phylum",
            },
        ),
        migrations.AddField(
            model_name="classification",
            name="phylum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="taxonomy.phylum"
            ),
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("remark", models.CharField(max_length=255, null=True)),
                (
                    "genus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.genus"
                    ),
                ),
            ],
            options={
                "db_table": "taxonomy_m_species",
            },
        ),
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_kana", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="taxonomy/breed")),
                ("remark", models.CharField(max_length=255, null=True)),
                (
                    "natural_monument",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomy.naturalmonument",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomy.species",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BreedTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.breed"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.tag"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="breed",
            constraint=models.UniqueConstraint(
                fields=("species", "name"), name="species_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="breedtags",
            constraint=models.UniqueConstraint(
                fields=("breed", "tag"), name="breed_tag_unique"
            ),
        ),
    ]
