# Generated by Django 5.1 on 2025-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EggProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(
                        help_text="データを記録した日付 (形式: YYYY-MM-DD)"
                    ),
                ),
                (
                    "weather_code",
                    models.IntegerField(
                        help_text="天気コード。具体的なコードの詳細はシステムで管理"
                    ),
                ),
                ("avg_temperature", models.FloatField(help_text="平均気温 (単位: °C)")),
                ("humidity", models.IntegerField(help_text="湿度 (単位: %)")),
                ("pressure", models.FloatField(help_text="気圧 (単位: hPa)")),
                ("rainfall", models.FloatField(help_text="降水量 (単位: mm)")),
                ("hen_count", models.IntegerField(help_text="メスの個体数 (単位: 羽)")),
                ("egg_count", models.IntegerField(help_text="産卵数 (単位: 個)")),
                (
                    "avg_egg_weight",
                    models.FloatField(help_text="卵の平均重量 (単位: g)"),
                ),
                (
                    "feed_weight",
                    models.IntegerField(help_text="消費した飼料の量 (単位: 125g／升)"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="自由記述フィールド。産卵に関するコメントや観察記録を記入",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
