# Generated by Django 6.0 on 2026-07-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="image",
            field=models.ImageField(blank=True, upload_to="taxonomy/breed"),
        ),
    ]
