# Generated by Django 6.0 on 2026-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_alter_breed_image"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="breed",
            name="species_name_unique",
        ),
        migrations.AddConstraint(
            model_name="breed",
            constraint=models.UniqueConstraint(
                fields=("name",), name="breed_name_unique"
            ),
        ),
    ]
