# Generated by Django 6.0 on 2026-07-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0003_remove_breed_species_name_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="natural_monument",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taxonomy.naturalmonument",
            ),
        ),
        migrations.AlterField(
            model_name="breed",
            name="remark",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
