# Generated by Django 6.0 on 2026-07-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0004_alter_breed_natural_monument_alter_breed_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivestockDistributionDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="データセット名"),
                ),
                (
                    "csv_file",
                    models.FileField(
                        upload_to="taxonomy/livestock_distribution",
                        verbose_name="畜産統計CSV",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(max_length=255, verbose_name="取得元名"),
                ),
                (
                    "source_stat_code",
                    models.CharField(max_length=20, verbose_name="政府統計コード"),
                ),
                (
                    "survey_year",
                    models.PositiveSmallIntegerField(verbose_name="対象年"),
                ),
                ("retrieved_at", models.DateField(verbose_name="ローカル取得日")),
                (
                    "source_url",
                    models.URLField(max_length=500, verbose_name="公開統計表URL"),
                ),
                ("note", models.TextField(blank=True, verbose_name="注意事項")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="表示対象"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "ordering": ["-retrieved_at", "-created_at"],
            },
        ),
    ]
