# Generated by Django 6.0 on 2026-07-12 09:04

from django.db import migrations, models


def deduplicate_livestock_distribution_datasets(apps, schema_editor):
    LivestockDistributionDataset = apps.get_model(
        "taxonomy", "LivestockDistributionDataset"
    )
    duplicate_keys = (
        LivestockDistributionDataset.objects.values("source_stat_code", "survey_year")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
    )
    for duplicate_key in duplicate_keys:
        datasets = list(
            LivestockDistributionDataset.objects.filter(
                source_stat_code=duplicate_key["source_stat_code"],
                survey_year=duplicate_key["survey_year"],
            ).order_by("-retrieved_at", "-created_at", "-id")
        )
        for dataset in datasets[1:]:
            dataset.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0005_livestockdistributiondataset"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_livestock_distribution_datasets,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="livestockdistributiondataset",
            constraint=models.UniqueConstraint(
                fields=("source_stat_code", "survey_year"),
                name="livestock_distribution_source_year_unique",
            ),
        ),
    ]
