# Generated by Django 6.0 on 2026-07-14 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taxonomy",
            "0006_livestockdistributiondataset_livestock_distribution_source_year_unique",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMTaxonomyCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "レビュー待ち"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="レビュー状態",
                    ),
                ),
                (
                    "kingdom_name",
                    models.CharField(max_length=255, verbose_name="界の名前"),
                ),
                (
                    "kingdom_name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="界の英名"
                    ),
                ),
                (
                    "phylum_name",
                    models.CharField(max_length=255, verbose_name="門の名前"),
                ),
                (
                    "phylum_name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="門の英名"
                    ),
                ),
                (
                    "classification_name",
                    models.CharField(max_length=255, verbose_name="綱の名前"),
                ),
                (
                    "classification_name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="綱の英名"
                    ),
                ),
                (
                    "family_name",
                    models.CharField(max_length=255, verbose_name="科の名前"),
                ),
                (
                    "family_name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="科の英名"
                    ),
                ),
                (
                    "genus_name",
                    models.CharField(max_length=255, verbose_name="属の名前"),
                ),
                (
                    "genus_name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="属の英名"
                    ),
                ),
                (
                    "species_name",
                    models.CharField(max_length=255, verbose_name="種の名前"),
                ),
                (
                    "species_name_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="種の英名"
                    ),
                ),
                (
                    "breed_name",
                    models.CharField(
                        max_length=255, verbose_name="品種・系統・分類対象名"
                    ),
                ),
                (
                    "breed_name_kana",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="品種・系統・分類対象名のよみがな",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(blank=True, max_length=255, verbose_name="出典名"),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, max_length=500, verbose_name="出典URL"),
                ),
                (
                    "external_taxon_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="外部taxonomy ID"
                    ),
                ),
                ("llm_note", models.TextField(blank=True, verbose_name="LLM生成メモ")),
                (
                    "review_note",
                    models.TextField(blank=True, verbose_name="レビュー確認メモ"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="レビュー日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "approved_breed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="taxonomy.breed",
                        verbose_name="承認後の品種",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="レビュー担当者",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-created_at"],
            },
        ),
    ]
