# Generated by Django 6.0 on 2026-07-14 14:48

from django.db import migrations


def move_review_note_to_llm_note(apps, schema_editor):
    candidate_model = apps.get_model("taxonomy", "LLMTaxonomyCandidate")
    candidates = []
    for candidate in candidate_model.objects.exclude(review_note=""):
        if candidate.llm_note:
            candidate.llm_note = (
                f"{candidate.llm_note}\nレビュー確認メモ: {candidate.review_note}"
            )
        else:
            candidate.llm_note = f"レビュー確認メモ: {candidate.review_note}"
        candidates.append(candidate)
    if candidates:
        candidate_model.objects.bulk_update(candidates, ["llm_note"])


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0007_llmtaxonomycandidate"),
    ]

    operations = [
        migrations.RunPython(
            move_review_note_to_llm_note,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="llmtaxonomycandidate",
            name="review_note",
        ),
    ]
