# Generated by Django 6.0 on 2026-07-14 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0008_remove_llm_candidate_review_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMTaxonomyCandidateGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "準備中"),
                            ("running", "生成中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ジョブ状態",
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="現在ステップ"
                    ),
                ),
                (
                    "current_target",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="現在の生成対象"
                    ),
                ),
                (
                    "target_names",
                    models.JSONField(
                        blank=True, default=list, verbose_name="生成対象名一覧"
                    ),
                ),
                (
                    "candidate_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="保存済み候補ID一覧"
                    ),
                ),
                (
                    "failures",
                    models.JSONField(
                        blank=True, default=list, verbose_name="失敗対象一覧"
                    ),
                ),
                (
                    "total_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="生成対象総数"
                    ),
                ),
                (
                    "processed_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="処理済み対象数"
                    ),
                ),
                (
                    "success_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="成功件数"
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="失敗件数"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラーメッセージ"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="開始日時"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
