# Generated by Django 6.0 on 2026-07-15 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0009_llmtaxonomycandidategenerationjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="llmtaxonomycandidategenerationjob",
            name="is_processing",
            field=models.BooleanField(default=False, verbose_name="処理中"),
        ),
        migrations.AddField(
            model_name="llmtaxonomycandidategenerationjob",
            name="processing_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processing_llm_taxonomy_generation_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="処理実行者",
            ),
        ),
        migrations.AddField(
            model_name="llmtaxonomycandidategenerationjob",
            name="processing_started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="処理開始日時"
            ),
        ),
    ]
