# Generated by Django 6.0 on 2026-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0010_llmtaxonomycandidategenerationjob_is_processing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmtaxonomycandidategenerationjob",
            name="processing_token",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="処理タブ識別子"
            ),
        ),
    ]
