# Generated by Django 6.0 on 2026-01-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_date", models.DateField(db_index=True)),
                ("session_number", models.IntegerField()),
                ("house", models.CharField(max_length=32)),
                ("committee", models.CharField(max_length=128)),
                ("meeting_number", models.CharField(max_length=32)),
                ("agenda_title", models.TextField()),
                ("agenda_order", models.IntegerField()),
                ("min_id", models.CharField(max_length=64)),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Speech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("speaker_name", models.CharField(max_length=128)),
                (
                    "speaker_role",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "speaker_affiliation",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("speech_text", models.TextField()),
                ("speech_order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speeches",
                        to="kokkai.meeting",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MeetingIndex",
        ),
    ]
