# Generated by Django 6.0 on 2026-01-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0002_meeting_speech_delete_meetingindex"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meeting",
            constraint=models.UniqueConstraint(
                fields=("min_id", "agenda_order"), name="unique_meeting_agenda"
            ),
        ),
    ]
