# Generated by Django 6.0 on 2026-01-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0003_meeting_unique_meeting_agenda'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(
                fields=('min_id',), name='unique_meeting_min_id'
            ),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='agenda_order',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='agenda_title',
        ),
    ]

