# Generated by Django 6.0 on 2026-08-25 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0004_remove_meeting_unique_meeting_agenda_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="pdf_url",
            field=models.URLField(blank=True, verbose_name="PDF URL"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="committee",
            field=models.CharField(max_length=128, verbose_name="会議名"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="house",
            field=models.CharField(max_length=32, verbose_name="院名"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_date",
            field=models.DateField(db_index=True, verbose_name="開催日"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_number",
            field=models.CharField(max_length=32, verbose_name="号数"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="min_id",
            field=models.CharField(max_length=64, verbose_name="会議録ID"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="session_number",
            field=models.IntegerField(verbose_name="国会回次"),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="url",
            field=models.URLField(verbose_name="会議録URL"),
        ),
        migrations.AlterField(
            model_name="speech",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="speech",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speeches",
                to="kokkai.meeting",
                verbose_name="会議録",
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="speaker_affiliation",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="発言者所属会派"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="speaker_name",
            field=models.CharField(max_length=128, verbose_name="発言者名"),
        ),
        migrations.AlterField(
            model_name="speech",
            name="speaker_role",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="発言者役割"
            ),
        ),
        migrations.AlterField(
            model_name="speech",
            name="speech_order",
            field=models.IntegerField(verbose_name="発言順"),
        ),
        migrations.AlterField(
            model_name="speech",
            name="speech_text",
            field=models.TextField(verbose_name="発言本文"),
        ),
    ]
