# Generated by Django 6.0 on 2026-08-26 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0005_meeting_pdf_url_alter_meeting_committee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_number', models.PositiveSmallIntegerField(verbose_name='選択肢番号')),
                ('text', models.TextField(verbose_name='選択肢')),
                ('is_correct', models.BooleanField(verbose_name='適切な選択')),
                ('rationale', models.TextField(verbose_name='選択根拠')),
            ],
            options={
                'ordering': ['choice_number'],
            },
        ),
        migrations.AddField(
            model_name='speech',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='発言URL'),
        ),
        migrations.CreateModel(
            name='MeetingScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='バージョン')),
                ('source_hash', models.CharField(db_index=True, max_length=64, verbose_name='元データハッシュ')),
                ('prompt_version', models.CharField(max_length=64, verbose_name='プロンプトバージョン')),
                ('generator_model', models.CharField(max_length=64, verbose_name='生成モデル')),
                ('status', models.CharField(choices=[('ready', '利用可能'), ('failed', '生成失敗')], default='ready', max_length=16, verbose_name='状態')),
                ('title', models.CharField(max_length=200, verbose_name='シナリオタイトル')),
                ('background', models.TextField(verbose_name='背景')),
                ('success_label', models.CharField(max_length=64, verbose_name='成功時の判定')),
                ('failure_label', models.CharField(max_length=64, verbose_name='失敗時の判定')),
                ('judgment_criteria', models.TextField(verbose_name='判定条件')),
                ('passing_score', models.PositiveSmallIntegerField(default=50, verbose_name='合格点')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='kokkai.meeting', verbose_name='会議録')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(verbose_name='表示順')),
                ('name', models.CharField(max_length=128, verbose_name='氏名')),
                ('role', models.CharField(blank=True, max_length=128, verbose_name='役職')),
                ('affiliation', models.CharField(blank=True, max_length=128, verbose_name='所属')),
                ('speech_count', models.PositiveIntegerField(default=0, verbose_name='発言数')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='kokkai.meetingscenario', verbose_name='シナリオ')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='プレイID')),
                ('next_turn_number', models.PositiveIntegerField(default=1, verbose_name='次のターン番号')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='正解数')),
                ('answer_count', models.PositiveIntegerField(default=0, verbose_name='回答数')),
                ('result_label', models.CharField(blank=True, max_length=64, verbose_name='最終判定')),
                ('result_explanation', models.TextField(blank=True, verbose_name='最終判定の説明')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays', to='kokkai.meetingscenario', verbose_name='シナリオ')),
                ('selected_actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays', to='kokkai.scenarioactor', verbose_name='担当アクター')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField(verbose_name='ターン番号')),
                ('dialogue', models.TextField(verbose_name='会話文')),
                ('evidence_note', models.TextField(verbose_name='根拠の説明')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='kokkai.scenarioactor', verbose_name='発言アクター')),
                ('evidence_speech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_turns', to='kokkai.speech', verbose_name='根拠発言')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='kokkai.meetingscenario', verbose_name='シナリオ')),
            ],
            options={
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioPlayAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='選択日時')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play_answers', to='kokkai.scenariochoice', verbose_name='選択肢')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kokkai.scenarioplay', verbose_name='プレイ')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play_answers', to='kokkai.scenarioturn', verbose_name='ターン')),
            ],
        ),
        migrations.AddField(
            model_name='scenariochoice',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='kokkai.scenarioturn', verbose_name='ターン'),
        ),
        migrations.AddIndex(
            model_name='meetingscenario',
            index=models.Index(fields=['meeting', 'source_hash', 'prompt_version', 'status'], name='kokkai_scenario_cache_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingscenario',
            constraint=models.UniqueConstraint(fields=('meeting', 'version'), name='unique_meeting_scenario_version'),
        ),
        migrations.AddConstraint(
            model_name='scenarioactor',
            constraint=models.UniqueConstraint(fields=('scenario', 'name', 'role', 'affiliation'), name='unique_scenario_actor_identity'),
        ),
        migrations.AddConstraint(
            model_name='scenarioturn',
            constraint=models.UniqueConstraint(fields=('scenario', 'turn_number'), name='unique_scenario_turn_number'),
        ),
        migrations.AddConstraint(
            model_name='scenarioplayanswer',
            constraint=models.UniqueConstraint(fields=('play', 'turn'), name='unique_play_turn_answer'),
        ),
        migrations.AddConstraint(
            model_name='scenariochoice',
            constraint=models.UniqueConstraint(fields=('turn', 'choice_number'), name='unique_scenario_choice_number'),
        ),
    ]
