# Generated by Django 6.0 on 2026-09-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0006_scenariochoice_speech_source_url_meetingscenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioturn',
            name='is_overview',
            field=models.BooleanField(default=False, verbose_name='全体要約ターン'),
        ),
        migrations.AlterField(
            model_name='scenarioturn',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='kokkai.scenarioactor', verbose_name='発言アクター'),
        ),
        migrations.AlterField(
            model_name='scenarioturn',
            name='evidence_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scenario_turns', to='kokkai.speech', verbose_name='根拠発言'),
        ),
    ]
