# Generated by Django 6.0 on 2026-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0007_scenarioturn_is_overview_alter_scenarioturn_actor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_current_catalog",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="現在のカタログ"
            ),
        ),
    ]
