# Generated by Django 6.0 on 2026-09-02 12:35

from django.db import migrations, models


def move_background_to_overview_turn(apps, schema_editor):
    """既存シナリオの背景をTurn 1の会議全体要約へ移す。"""
    MeetingScenario = apps.get_model("kokkai", "MeetingScenario")
    ScenarioPlay = apps.get_model("kokkai", "ScenarioPlay")
    ScenarioTurn = apps.get_model("kokkai", "ScenarioTurn")

    for scenario in MeetingScenario.objects.iterator():
        turns = ScenarioTurn.objects.filter(scenario_id=scenario.pk)
        if turns.filter(is_overview=True).exists():
            continue
        if turns.exists():
            turns.update(turn_number=models.F("turn_number") + 1_000_000)
            turns.update(turn_number=models.F("turn_number") - 999_999)
            ScenarioPlay.objects.filter(
                scenario_id=scenario.pk, completed_at__isnull=True
            ).update(next_turn_number=models.F("next_turn_number") + 1)
        ScenarioTurn.objects.create(
            scenario_id=scenario.pk,
            turn_number=1,
            is_overview=True,
            dialogue=scenario.background,
            evidence_note="会議録全体を見渡した要約です。",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0008_meeting_is_current_catalog"),
    ]

    operations = [
        migrations.RunPython(
            move_background_to_overview_turn, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name="meetingscenario",
            name="background",
        ),
    ]
