# Generated by Django 6.0 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


def move_overview_to_scenario(apps, schema_editor):
    """既存シナリオの要約をシナリオ属性へ移し、発言ターンを詰める。"""
    MeetingScenario = apps.get_model("kokkai", "MeetingScenario")
    ScenarioPlay = apps.get_model("kokkai", "ScenarioPlay")
    ScenarioTurn = apps.get_model("kokkai", "ScenarioTurn")

    for scenario in MeetingScenario.objects.iterator():
        overview_turns = ScenarioTurn.objects.filter(
            scenario_id=scenario.pk, is_overview=True
        ).order_by("turn_number")
        overview_turn = overview_turns.first()
        if overview_turn is None:
            continue

        scenario.overview = overview_turn.dialogue
        scenario.save(update_fields=["overview"])
        overview_turns.delete()

        speech_turns = list(
            ScenarioTurn.objects.filter(scenario_id=scenario.pk).order_by(
                "-turn_number"
            )
        )
        for turn in speech_turns:
            turn.turn_number += 1_000_000
            turn.save(update_fields=["turn_number"])
        for turn in speech_turns:
            turn.turn_number -= 1_000_001
            turn.save(update_fields=["turn_number"])

        for play in ScenarioPlay.objects.filter(scenario_id=scenario.pk):
            if play.next_turn_number > 1:
                play.next_turn_number -= 1
                play.save(update_fields=["next_turn_number"])


def restore_overview_turn(apps, schema_editor):
    """シナリオ属性の要約を、旧形式の先頭ターンへ戻す。"""
    MeetingScenario = apps.get_model("kokkai", "MeetingScenario")
    ScenarioPlay = apps.get_model("kokkai", "ScenarioPlay")
    ScenarioTurn = apps.get_model("kokkai", "ScenarioTurn")

    for scenario in MeetingScenario.objects.iterator():
        if ScenarioTurn.objects.filter(
            scenario_id=scenario.pk, is_overview=True
        ).exists():
            continue

        speech_turns = list(
            ScenarioTurn.objects.filter(scenario_id=scenario.pk).order_by(
                "-turn_number"
            )
        )
        for turn in speech_turns:
            turn.turn_number += 1_000_000
            turn.save(update_fields=["turn_number"])
        for turn in speech_turns:
            turn.turn_number -= 999_999
            turn.save(update_fields=["turn_number"])

        ScenarioTurn.objects.create(
            scenario_id=scenario.pk,
            turn_number=1,
            is_overview=True,
            dialogue=scenario.overview,
            evidence_note="会議録全体を見渡した要約です。",
        )
        ScenarioPlay.objects.filter(scenario_id=scenario.pk).update(
            next_turn_number=models.F("next_turn_number") + 1
        )


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0009_remove_meetingscenario_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingscenario",
            name="overview",
            field=models.TextField(default="", verbose_name="会議全体の要約"),
            preserve_default=False,
        ),
        migrations.RunPython(move_overview_to_scenario, restore_overview_turn),
        migrations.RemoveField(
            model_name="scenarioturn",
            name="is_overview",
        ),
        migrations.AlterField(
            model_name="scenarioturn",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="turns",
                to="kokkai.scenarioactor",
                verbose_name="発言アクター",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioturn",
            name="evidence_speech",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scenario_turns",
                to="kokkai.speech",
                verbose_name="根拠発言",
            ),
        ),
    ]
