# Generated by Django 6.0 on 2026-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0010_move_overview_to_meeting_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariochoice",
            name="prompt_version",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="選択肢プロンプトバージョン",
            ),
        ),
    ]
