# Generated by Django 6.0 on 2026-09-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0011_scenariochoice_prompt_version"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scenariochoice",
            name="unique_scenario_choice_number",
        ),
        migrations.AddField(
            model_name="scenariochoice",
            name="play",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="kokkai.scenarioplay",
                verbose_name="プレイ",
            ),
        ),
        migrations.AddConstraint(
            model_name="scenariochoice",
            constraint=models.UniqueConstraint(
                fields=("play", "turn", "choice_number", "prompt_version"),
                name="unique_scenario_play_choice_version_number",
            ),
        ),
    ]
