# Generated by Django 6.0 on 2026-09-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0012_remove_scenariochoice_unique_scenario_choice_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariochoice",
            name="play",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="choices",
                to="kokkai.scenarioplay",
                verbose_name="プレイ",
            ),
        ),
    ]
