# Generated by Django 6.0 on 2026-09-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0013_alter_scenariochoice_play"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="is_current_catalog",
        ),
    ]
