# Generated by Django 6.0 on 2026-09-04 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0014_remove_meeting_is_current_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenarioplay",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plays",
                to="kokkai.meetingscenario",
                verbose_name="シナリオ",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioplay",
            name="selected_actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plays",
                to="kokkai.scenarioactor",
                verbose_name="担当アクター",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioplayanswer",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="play_answers",
                to="kokkai.scenariochoice",
                verbose_name="選択肢",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioplayanswer",
            name="turn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="play_answers",
                to="kokkai.scenarioturn",
                verbose_name="ターン",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioturn",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turns",
                to="kokkai.scenarioactor",
                verbose_name="発言アクター",
            ),
        ),
        migrations.AlterField(
            model_name="scenarioturn",
            name="evidence_speech",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario_turns",
                to="kokkai.speech",
                verbose_name="根拠発言",
            ),
        ),
    ]
