# Generated by Django 6.0 on 2026-09-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0015_alter_scenarioplay_scenario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(verbose_name='表示順')),
                ('name', models.CharField(max_length=128, verbose_name='氏名')),
                ('name_yomi', models.CharField(blank=True, max_length=128, verbose_name='氏名よみ')),
                ('attendance_type', models.CharField(choices=[('chair', '委員長'), ('director', '理事'), ('committee_member', '出席委員'), ('government_official', '国務大臣等'), ('government_reference', '政府参考人'), ('reference', '参考人'), ('witness', '証人'), ('public_witness', '公述人'), ('staff', '事務局等'), ('other', 'その他'), ('speaker_only', '発言者（出席情報未確認）')], default='other', max_length=32, verbose_name='出席種別')),
                ('attendance_role', models.CharField(blank=True, max_length=128, verbose_name='出席時の役職')),
                ('speaker_position', models.CharField(blank=True, max_length=128, verbose_name='発言時の肩書き')),
                ('speaker_role', models.CharField(blank=True, max_length=128, verbose_name='発言時の役割')),
                ('affiliation', models.CharField(blank=True, max_length=128, verbose_name='発言時の所属')),
                ('has_spoken', models.BooleanField(default=False, verbose_name='発言有無')),
                ('speech_count', models.PositiveIntegerField(default=0, verbose_name='発言数')),
                ('source_meeting_id', models.CharField(max_length=64, verbose_name='根拠会議録ID')),
                ('source_url', models.URLField(blank=True, verbose_name='根拠会議録URL')),
                ('source_text', models.TextField(blank=True, verbose_name='抽出元テキスト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='kokkai.meeting', verbose_name='会議録')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipantEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('attendance', '出席者一覧'), ('speech', '発言記録')], max_length=16, verbose_name='根拠種別')),
                ('source_meeting_id', models.CharField(max_length=64, verbose_name='根拠会議録ID')),
                ('source_speech_id', models.CharField(blank=True, max_length=64, verbose_name='根拠発言ID')),
                ('source_url', models.URLField(blank=True, verbose_name='根拠URL')),
                ('source_text', models.TextField(verbose_name='抽出元テキスト')),
                ('speech_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='発言順')),
                ('speaker_position', models.CharField(blank=True, max_length=128, verbose_name='発言時の肩書き')),
                ('speaker_role', models.CharField(blank=True, max_length=128, verbose_name='発言時の役割')),
                ('affiliation', models.CharField(blank=True, max_length=128, verbose_name='発言時の所属')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='kokkai.meetingparticipant', verbose_name='会議参加者')),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'name'), name='unique_meeting_participant_name'),
        ),
    ]
