# Generated by Django 6.0 on 2026-09-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0016_meetingparticipant_meetingparticipantevidence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingparticipantevidence',
            options={'ordering': ['source_type', 'speech_order', 'pk']},
        ),
    ]
