# Generated by Django 6.0 on 2026-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0017_alter_meetingparticipantevidence_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingparticipant",
            name="attendance_type",
            field=models.CharField(
                choices=[
                    ("chair", "委員長"),
                    ("director", "理事"),
                    ("committee_member", "出席委員"),
                    ("government_official", "国務大臣等"),
                    ("government_reference", "政府参考人"),
                    ("reference", "参考人"),
                    ("witness", "証人"),
                    ("public_witness", "公述人"),
                    ("staff", "事務局等"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=32,
                verbose_name="出席種別",
            ),
        ),
    ]
