# Generated by Django 6.0 on 2026-09-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0018_alter_meetingparticipant_attendance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='attendance_role',
        ),
        migrations.RemoveField(
            model_name='meetingparticipant',
            name='attendance_type',
        ),
    ]
