# Generated by Django 6.0 on 2026-09-05 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0019_remove_meetingparticipant_attendance_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingSupportDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="入力URL")),
                ("source_text", models.TextField(verbose_name="入力本文")),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="生成モデル"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "確認待ち"),
                            ("imported", "登録済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="エラー")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kokkai_reading_support_drafts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ReadingSupportEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("term", "用語"), ("reading_override", "読み補正")],
                        default="term",
                        max_length=32,
                        verbose_name="種別",
                    ),
                ),
                ("surface", models.CharField(max_length=255, verbose_name="表記")),
                (
                    "normalized_surface",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        unique=True,
                        verbose_name="正規化表記",
                    ),
                ),
                ("reading", models.CharField(max_length=255, verbose_name="読み")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="カテゴリ"
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="出典URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "ordering": ["surface", "pk"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "entry_type"],
                        name="kokkai_reading_active_type_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReadingSupportDraftCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("term", "用語"), ("reading_override", "読み補正")],
                        default="term",
                        max_length=32,
                        verbose_name="種別",
                    ),
                ),
                ("surface", models.CharField(max_length=255, verbose_name="表記")),
                (
                    "reading",
                    models.CharField(blank=True, max_length=255, verbose_name="読み"),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="カテゴリ"
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="出典URL")),
                (
                    "needs_review",
                    models.BooleanField(default=True, verbose_name="要確認"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="登録承認"),
                ),
                (
                    "is_registered",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="登録済み"
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="確認メモ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="kokkai.readingsupportdraft",
                        verbose_name="下書き",
                    ),
                ),
                (
                    "registered_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_candidates",
                        to="kokkai.readingsupportentry",
                        verbose_name="登録先",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
