# Generated by Django 6.0 on 2026-09-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0021_seed_reading_support_dictionary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readingsupportdraftcandidate",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="readingsupportdraftcandidate",
            name="registered_entry",
        ),
        migrations.DeleteModel(
            name="ReadingSupportDraft",
        ),
        migrations.DeleteModel(
            name="ReadingSupportDraftCandidate",
        ),
    ]
