# Generated by Django 6.0 on 2026-09-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0022_remove_readingsupportdraftcandidate_draft_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readingsupportentry",
            name="category",
        ),
    ]
