# Generated by Django 6.0 on 2026-09-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0023_remove_readingsupportentry_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="readingsupportentry",
            name="kokkai_reading_active_type_idx",
        ),
        migrations.RemoveField(
            model_name="readingsupportentry",
            name="entry_type",
        ),
    ]
