# Generated by Django 6.0 on 2026-09-06 14:54

from django.db import migrations


def delete_inactive_entries(apps, schema_editor):
    """Remove entries that were disabled before the active flag was removed."""
    entry_model = apps.get_model("kokkai", "ReadingSupportEntry")
    entry_model.objects.filter(is_active=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "kokkai",
            "0024_remove_readingsupportentry_kokkai_reading_active_type_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            delete_inactive_entries,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="readingsupportentry",
            name="is_active",
        ),
    ]
