# Generated by Django 5.1.7 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0025_remove_readingsupportentry_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="readingsupportentry",
            old_name="surface",
            new_name="word",
        ),
        migrations.RenameField(
            model_name="readingsupportentry",
            old_name="normalized_surface",
            new_name="normalized_word",
        ),
        migrations.AlterField(
            model_name="readingsupportentry",
            name="word",
            field=models.CharField(max_length=255, verbose_name="単語"),
        ),
        migrations.AlterField(
            model_name="readingsupportentry",
            name="normalized_word",
            field=models.CharField(
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="正規化単語",
            ),
        ),
        migrations.AlterModelOptions(
            name="readingsupportentry",
            options={"ordering": ["word", "pk"]},
        ),
    ]
