# Generated by Django 5.1.7 on 2026-09-13

from django.db import migrations, models


def fill_missing_descriptions(apps, schema_editor):
    """既存の読み補正項目にも、辞書項目としての説明を付ける。"""
    entry_model = apps.get_model("kokkai", "ReadingSupportEntry")
    entry_model.objects.filter(description="").update(
        description="読み仮名を補正するための登録語です。"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0026_rename_reading_support_entry_word_fields"),
    ]

    operations = [
        migrations.RunPython(fill_missing_descriptions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="readingsupportentry",
            name="description",
            field=models.TextField(verbose_name="説明"),
        ),
    ]
