# Generated by Django 6.0 on 2026-09-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0027_require_reading_support_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='正規化氏名')),
                ('name_yomi', models.CharField(blank=True, max_length=128, verbose_name='氏名よみ')),
                ('identity_status', models.CharField(choices=[('unconfirmed', '未確認')], default='unconfirmed', max_length=16, verbose_name='人物同定状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'ordering': ['name', 'name_yomi', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('name', 'name_yomi'), name='unique_observed_person_name_yomi')],
            },
        ),
        migrations.CreateModel(
            name='AffiliationObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_on', models.DateField(db_index=True, verbose_name='観測日')),
                ('affiliation', models.CharField(blank=True, max_length=128, verbose_name='観測会派')),
                ('speaker_position', models.CharField(blank=True, max_length=128, verbose_name='発言時の肩書き')),
                ('speaker_role', models.CharField(blank=True, max_length=128, verbose_name='発言時の役割')),
                ('speech_count', models.PositiveIntegerField(default=0, verbose_name='発言・観測件数')),
                ('source_meeting_id', models.CharField(max_length=64, verbose_name='根拠会議録ID')),
                ('source_url', models.URLField(blank=True, verbose_name='根拠会議録URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_observations', to='kokkai.meeting', verbose_name='会議録')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_observations', to='kokkai.observedperson', verbose_name='観測対象')),
            ],
            options={
                'ordering': ['observed_on', 'meeting_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AffiliationObservationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_speech_id', models.CharField(max_length=64, verbose_name='根拠発言ID')),
                ('source_url', models.URLField(blank=True, verbose_name='根拠発言URL')),
                ('source_text', models.TextField(verbose_name='根拠発言本文')),
                ('speech_order', models.PositiveIntegerField(verbose_name='発言順')),
                ('speaker_position', models.CharField(blank=True, max_length=128, verbose_name='発言時の肩書き')),
                ('speaker_role', models.CharField(blank=True, max_length=128, verbose_name='発言時の役割')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='kokkai.affiliationobservation', verbose_name='会派観測')),
            ],
            options={
                'ordering': ['speech_order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('observation', 'source_speech_id'), name='unique_affiliation_observation_speech')],
            },
        ),
        migrations.AddConstraint(
            model_name='affiliationobservation',
            constraint=models.UniqueConstraint(fields=('person', 'meeting', 'affiliation'), name='unique_person_meeting_affiliation_observation'),
        ),
    ]
