# Generated by Django 6.0 on 2026-09-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0028_observedperson_affiliationobservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationobservation',
            name='source_type',
            field=models.CharField(choices=[('speech', '発言')], default='speech', max_length=16, verbose_name='観測種別'),
        ),
    ]
