# Generated by Django 6.0 on 2026-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0029_affiliationobservation_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='source_speech_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='発言ID'),
        ),
        migrations.AddField(
            model_name='speech',
            name='speaker_position',
            field=models.CharField(blank=True, max_length=128, verbose_name='発言者肩書き'),
        ),
        migrations.AddField(
            model_name='speech',
            name='speaker_yomi',
            field=models.CharField(blank=True, max_length=128, verbose_name='発言者よみ'),
        ),
    ]
