# Generated by Django 6.0 on 2026-09-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0030_speech_source_speech_id_speech_speaker_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='affiliationobservation',
            name='unique_person_meeting_affiliation_observation',
        ),
        migrations.AlterField(
            model_name='affiliationobservation',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_observations', to='kokkai.meeting', verbose_name='会議録'),
        ),
        migrations.AddConstraint(
            model_name='affiliationobservation',
            constraint=models.UniqueConstraint(fields=('person', 'source_meeting_id', 'affiliation'), name='unique_person_source_meeting_affiliation_observation'),
        ),
    ]
