# Generated by Django 6.0 on 2026-09-28 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kokkai', '0031_remove_affiliationobservation_unique_person_meeting_affiliation_observation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='取得開始日')),
                ('end_date', models.DateField(verbose_name='取得終了日')),
                ('current_start_date', models.DateField(verbose_name='現在の取得開始日')),
                ('current_end_date', models.DateField(verbose_name='現在の取得終了日')),
                ('next_record_position', models.PositiveIntegerField(default=1, verbose_name='次のAPIレコード位置')),
                ('current_period_record_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='現在の月次期間の会議録数')),
                ('processed_meeting_count', models.PositiveIntegerField(default=0, verbose_name='反映済み会議録数')),
                ('status', models.CharField(choices=[('pending', '開始待ち'), ('running', '取得中'), ('completed', '完了'), ('failed', '再開待ち')], default='pending', max_length=16, verbose_name='取得状態')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='通信失敗理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
