# Generated by Django 6.0 on 2026-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kokkai", "0032_affiliationimportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="readingsupportentry",
            name="generated_by_model",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="生成モデル"
            ),
        ),
    ]
