# Generated by Django 5.1 on 2024-10-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "edinet_code",
                    models.CharField(
                        max_length=6, null=True, verbose_name="ＥＤＩＮＥＴコード"
                    ),
                ),
                (
                    "type_of_submitter",
                    models.CharField(
                        max_length=30, null=True, verbose_name="提出者種別"
                    ),
                ),
                (
                    "listing_status",
                    models.CharField(max_length=3, null=True, verbose_name="上場区分"),
                ),
                (
                    "consolidated_status",
                    models.CharField(
                        max_length=1, null=True, verbose_name="連結の有無"
                    ),
                ),
                ("capital", models.IntegerField(null=True, verbose_name="資本金")),
                (
                    "end_fiscal_year",
                    models.CharField(max_length=6, null=True, verbose_name="決算日"),
                ),
                (
                    "submitter_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="提出者名"
                    ),
                ),
                (
                    "submitter_name_en",
                    models.CharField(
                        max_length=100, null=True, verbose_name="提出者名（英字）"
                    ),
                ),
                (
                    "submitter_name_kana",
                    models.CharField(
                        max_length=100, null=True, verbose_name="提出者名（ヨミ）"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, null=True, verbose_name="所在地"),
                ),
                (
                    "submitter_industry",
                    models.CharField(
                        max_length=25, null=True, verbose_name="提出者業種"
                    ),
                ),
                (
                    "securities_code",
                    models.CharField(
                        max_length=5, null=True, verbose_name="証券コード"
                    ),
                ),
                (
                    "corporate_number",
                    models.CharField(
                        max_length=13, null=True, verbose_name="提出者法人番号"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReportDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq_number", models.SmallIntegerField(verbose_name="連番")),
                ("doc_id", models.CharField(max_length=8, verbose_name="書類管理番号")),
                (
                    "ordinance_code",
                    models.CharField(max_length=3, verbose_name="府令コード"),
                ),
                (
                    "form_code",
                    models.CharField(max_length=6, verbose_name="様式コード"),
                ),
                ("period_start", models.DateField(verbose_name="期間（自）")),
                ("period_end", models.DateField(verbose_name="期間（至）")),
                ("submit_date_time", models.DateTimeField(verbose_name="提出日時")),
                (
                    "doc_description",
                    models.CharField(max_length=147, verbose_name="提出書類概要"),
                ),
                (
                    "ope_date_time",
                    models.DateTimeField(null=True, verbose_name="操作日時"),
                ),
                (
                    "withdrawal_status",
                    models.CharField(max_length=1, verbose_name="取下区分"),
                ),
                (
                    "doc_info_edit_status",
                    models.CharField(max_length=1, verbose_name="書類情報修正区分"),
                ),
                (
                    "disclosure_status",
                    models.CharField(max_length=1, verbose_name="開示不開示区分"),
                ),
                ("xbrl_flag", models.BooleanField(verbose_name="XBRL有無フラグ")),
                ("pdf_flag", models.BooleanField(verbose_name="PDF有無フラグ")),
                (
                    "english_doc_flag",
                    models.BooleanField(verbose_name="英文ファイル有無フラグ"),
                ),
                ("csv_flag", models.BooleanField(verbose_name="CSV有無フラグ")),
                ("legal_status", models.BooleanField(verbose_name="縦覧区分")),
                ("download_reserved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="securities.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Counting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(null=True, verbose_name="期間（自）"),
                ),
                ("period_end", models.DateField(null=True, verbose_name="期間（至）")),
                ("submit_date", models.DateField(verbose_name="提出日時")),
                (
                    "avg_salary",
                    models.IntegerField(null=True, verbose_name="平均年間給与（円）"),
                ),
                (
                    "avg_tenure",
                    models.FloatField(null=True, verbose_name="平均勤続年数（年）"),
                ),
                (
                    "avg_age",
                    models.FloatField(null=True, verbose_name="平均年齢（歳）"),
                ),
                (
                    "number_of_employees",
                    models.IntegerField(null=True, verbose_name="従業員数（人）"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="securities.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "submit_date")},
            },
        ),
    ]
