# Generated by Django 6.0 on 2026-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fiscal_year_end_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='決算期の確認日時'),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_end_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='決算期の取得元'),
        ),
    ]
