# Generated by Django 6.0 on 2025-12-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="SectorDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rs_20d", models.FloatField()),
                ("rs_slope_5d", models.FloatField()),
                ("rank", models.IntegerField()),
                ("rank_delta_5d", models.IntegerField()),
                ("signal", models.CharField(max_length=10)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="usa_research.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "rank"],
                "unique_together": {("date", "sector")},
            },
        ),
    ]
