# Generated by Django 6.0 on 2025-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0002_sector_sectordailysnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="MacroIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("ism_pmi", models.FloatField(blank=True, null=True)),
                ("us_10y_yield", models.FloatField(blank=True, null=True)),
                ("vix", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
