# Generated by Django 6.0 on 2025-12-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0003_macroindicator"),
    ]

    operations = [
        migrations.CreateModel(
            name="MsciCountryWeightReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="MSCI", max_length=100)),
                ("report_date", models.DateField(unique=True)),
                ("summary_md", models.TextField()),
                ("pdf_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
    ]
