# Generated by Django 6.0 on 2025-12-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0004_mscicountryweightreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("symbol", models.CharField(max_length=10)),
                ("price", models.FloatField()),
            ],
            options={
                "ordering": ["-date", "symbol"],
                "unique_together": {("date", "symbol")},
            },
        ),
    ]
