# Generated by Django 6.0 on 2025-12-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0005_assetprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nasdaq100Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("sector", models.CharField(max_length=100)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("as_of", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
    ]
