# Generated by Django 6.0 on 2026-03-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0006_nasdaq100company"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FinancialResultWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_date", models.DateField(verbose_name="Note公開日")),
                ("quarter", models.SmallIntegerField(verbose_name="四半期")),
                ("eps_ok", models.BooleanField(null=True, verbose_name="EPS達成")),
                ("sales_ok", models.BooleanField(null=True, verbose_name="売上達成")),
                (
                    "guidance_ok",
                    models.BooleanField(null=True, verbose_name="ガイダンス達成"),
                ),
                ("eps_estimate", models.FloatField(verbose_name="EPS予想")),
                ("eps_actual", models.FloatField(verbose_name="EPS実績")),
                ("sales_estimate", models.FloatField(verbose_name="売上予想")),
                ("sales_actual", models.FloatField(verbose_name="売上実績")),
                (
                    "y_over_y_growth_rate",
                    models.FloatField(verbose_name="前年同期比(%)"),
                ),
                (
                    "note_url",
                    models.URLField(blank=True, null=True, verbose_name="NoteURL"),
                ),
                ("ticker", models.CharField(max_length=10, verbose_name="ティッカー")),
                (
                    "eps_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="r_eps_unit",
                        to="usa_research.unit",
                        verbose_name="EPS単位",
                    ),
                ),
                (
                    "sales_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="r_sales_unit",
                        to="usa_research.unit",
                        verbose_name="売上単位",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_date", "ticker"],
            },
        ),
    ]
