# Generated by Django 6.0 on 2026-03-30 12:43

from django.db import migrations


def fix_garbled_units(apps, schema_editor):
    Unit = apps.get_model("usa_research", "Unit")
    # 文字化けしている（replacement characterを含む）「セント」単位を修正
    # ID=1が「セント」であることを想定
    try:
        u = Unit.objects.get(id=1)
        # もし文字化けした状態、または現在の状態にかかわらず「セント」に強制上書き（USA株のEPSは一般的にセントのため）
        u.name = "セント"
        u.save()
    except Unit.DoesNotExist:
        # ID=1が存在しない場合は、新規作成を試みる（既存データのマイグレーション用）
        Unit.objects.get_or_create(id=1, defaults={"name": "セント"})


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0007_unit_financialresultwatch"),
    ]

    operations = [
        migrations.RunPython(fix_garbled_units),
    ]
