# Generated by Django 6.0 on 2026-03-30 12:45

from django.db import migrations


def refine_unit_names(apps, schema_editor):
    Unit = apps.get_model("usa_research", "Unit")
    try:
        unit1 = Unit.objects.get(id=1)
        unit1.name = "セント(¢)"
        unit1.save()
    except Unit.DoesNotExist:
        pass

    try:
        unit2 = Unit.objects.get(id=2)
        unit2.name = "ドル(100M$)"
        unit2.save()
    except Unit.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0008_fix_unit_garbled_text"),
    ]

    operations = [
        migrations.RunPython(refine_unit_names),
    ]
