# Generated by Django 6.0 on 2026-03-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0009_refine_unit_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                (
                    "url_file_name",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
