# Generated by Django 6.0 on 2026-03-31 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0011_financialresultwatch_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialresultwatch",
            name="ticker",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="ティッカー"
            ),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="登録ユーザー",
            ),
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usa_research.market",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="financialresultwatch",
            name="symbol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_results",
                to="usa_research.symbol",
                verbose_name="シンボル",
            ),
        ),
        migrations.AddConstraint(
            model_name="symbol",
            constraint=models.UniqueConstraint(
                fields=("code", "market_id"), name="usa_code_market_id_unique"
            ),
        ),
    ]
