# Generated by Django 6.0 on 2026-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0013_sbisymbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rssfeed",
            name="link",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
