# Generated by Django 5.1 on 2025-01-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jp_stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
