# Generated by Django 5.1 on 2025-01-18 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jp_stocks", "0002_alter_order_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="fulfilled_quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
