# Generated by Django 6.0 on 2026-10-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApacheAccessReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="対象期間開始")),
                ("period_end", models.DateTimeField(verbose_name="対象期間終了")),
                (
                    "generated_at",
                    models.DateTimeField(db_index=True, verbose_name="生成日時"),
                ),
                (
                    "total_requests",
                    models.PositiveIntegerField(verbose_name="リクエスト総数"),
                ),
                ("status_401", models.PositiveIntegerField(verbose_name="401 件数")),
                ("status_403", models.PositiveIntegerField(verbose_name="403 件数")),
                ("status_404", models.PositiveIntegerField(verbose_name="404 件数")),
                ("status_5xx", models.PositiveIntegerField(verbose_name="5xx 件数")),
                (
                    "failure_sources",
                    models.PositiveIntegerField(verbose_name="失敗応答の送信元数"),
                ),
                (
                    "top_source_failures",
                    models.PositiveIntegerField(
                        verbose_name="送信元別失敗応答の最大件数"
                    ),
                ),
                (
                    "login_requests",
                    models.PositiveIntegerField(
                        verbose_name="ログイン先リクエスト件数"
                    ),
                ),
                (
                    "top_source_login_requests",
                    models.PositiveIntegerField(
                        verbose_name="送信元別ログイン先リクエストの最大件数"
                    ),
                ),
                (
                    "sensitive_path_successes",
                    models.PositiveIntegerField(
                        verbose_name="要注意パス候補への 2xx 件数"
                    ),
                ),
                (
                    "recent_failures",
                    models.PositiveIntegerField(verbose_name="期間後半の失敗応答件数"),
                ),
                (
                    "previous_failures",
                    models.PositiveIntegerField(verbose_name="期間前半の失敗応答件数"),
                ),
                (
                    "malformed_lines",
                    models.PositiveIntegerField(verbose_name="解析できなかった行数"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApacheReportDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終送信日時"
                    ),
                ),
            ],
        ),
    ]
