# Generated by Django 5.1 on 2024-10-04 15:10

import django.db.models.deletion
from django.db import migrations, models

import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="記事タイトル"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=home.models.get_random_filename,
                        verbose_name="画像",
                    ),
                ),
                ("summary", models.TextField(verbose_name="記事概要")),
                ("content", models.TextField(verbose_name="記事内容")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, verbose_name="ピックアップ記事として選択"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.category",
                        verbose_name="記事カテゴリー",
                    ),
                ),
            ],
        ),
    ]
