# Generated by Django 5.1 on 2024-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_post_author_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="home/posts/"),
        ),
    ]
