# Generated by Django 5.1 on 2024-09-28 21:07

from django.db import migrations, models

import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=home.models.get_random_filename
            ),
        ),
    ]
