# Generated by Django 5.1 on 2024-09-29 08:28

import django.db.models.deletion
from django.db import migrations, models

import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_post_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="home.category",
                verbose_name="記事カテゴリー",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="記事内容"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=home.models.get_random_filename,
                verbose_name="画像",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="ピックアップ"),
        ),
        migrations.AlterField(
            model_name="post",
            name="summary",
            field=models.TextField(verbose_name="記事概要"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="記事タイトル"),
        ),
    ]
