# Generated by Django 5.1 on 2024-09-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_post_category_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="ピックアップ記事として選択"
            ),
        ),
    ]
