# Generated by Django 5.2.5 on 2025-08-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="福祉事務所名")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="郵便番号"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="住所")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="FAX番号"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="緯度"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="経度"),
                ),
                (
                    "coordinate_system",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="座標系"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "福祉事務所",
                "verbose_name_plural": "福祉事務所一覧",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FacilityAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="この空き状況情報が対象とする年月（月末日が保存されます）",
                        verbose_name="対象年月",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "空きあり"),
                            ("limited", "残りわずか"),
                            ("unavailable", "空きなし"),
                        ],
                        default="unavailable",
                        max_length=20,
                        verbose_name="空き状況",
                    ),
                ),
                (
                    "available_count",
                    models.PositiveIntegerField(default=0, verbose_name="空き人数"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="備考"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="welfare_services.facility",
                        verbose_name="福祉事務所",
                    ),
                ),
            ],
            options={
                "verbose_name": "空き状況",
                "verbose_name_plural": "空き状況一覧",
                "ordering": ["-updated_at"],
                "unique_together": {("facility", "target_date")},
            },
        ),
        migrations.CreateModel(
            name="FacilityReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affiliated_facility_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="民間事業所名",
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(max_length=100, verbose_name="投稿者名"),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("physical", "身体障害者手帳"),
                            ("intellectual", "療育手帳"),
                            ("mental", "精神障害者保健福祉手帳"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="手帳の種類",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(max_length=50, verbose_name="手帳番号"),
                ),
                (
                    "certificate_grade",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="等級"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "★"),
                            (2, "★★"),
                            (3, "★★★"),
                            (4, "★★★★"),
                            (5, "★★★★★"),
                        ],
                        verbose_name="評価",
                    ),
                ),
                ("comment", models.TextField(verbose_name="コメント")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="承認済み"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="welfare_services.facility",
                        verbose_name="福祉事務所",
                    ),
                ),
            ],
            options={
                "verbose_name": "福祉事務所レビュー",
                "verbose_name_plural": "福祉事務所レビュー一覧",
                "ordering": ["-created_at"],
                "unique_together": {("certificate_type", "certificate_number")},
            },
        ),
    ]
