# Generated by Django 5.1 on 2024-12-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlogswithline",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "user"),
                    ("ASSISTANT", "assistant"),
                    ("SYSTEM", "system"),
                ],
                max_length=9,
            ),
        ),
    ]
