# Generated by Django 5.1 on 2024-12-14 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0002_alter_chatlogswithline_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChatLogsWithLine",
            new_name="ChatLogs",
        ),
    ]
