# Generated by Django 5.1 on 2024-12-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0003_rename_chatlogswithline_chatlogs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatlogs",
            name="file_path",
        ),
        migrations.AddField(
            model_name="chatlogs",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="llm_chat/audios/"),
        ),
    ]
