# Generated by Django 6.0 on 2026-03-08 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0004_remove_chatlogs_file_path_chatlogs_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatlogs",
            name="invisible",
        ),
    ]
