# Generated by Django 6.0 on 2026-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0005_remove_chatlogs_invisible"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlogs",
            name="mode_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatlogs",
            name="model_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
