# Generated by Django 6.0 on 2026-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0006_chatlogs_mode_name_chatlogs_model_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatlogs",
            name="mode_name",
        ),
        migrations.AddField(
            model_name="chatlogs",
            name="is_riddle",
            field=models.BooleanField(default=False),
        ),
    ]
