# Generated by Django 6.0 on 2026-03-11 14:05

from django.db import migrations, models


def migrate_is_riddle_to_use_case_type(apps, schema_editor):
    """
    既存の is_riddle データを use_case_type に移行する。
    is_riddle=True の場合は "Riddle" に設定。
    それ以外は model_name から推定するが、既存データには model_name が
    ユースケース名として入っているため、そのまま使用する。
    """
    ChatLogs = apps.get_model('llm_chat', 'ChatLogs')

    for log in ChatLogs.objects.all():
        # is_riddle が True の場合は Riddle
        if hasattr(log, 'is_riddle') and log.is_riddle:
            log.use_case_type = "Riddle"
        # model_name がある場合は、それがユースケース名として入っている可能性が高い
        # （旧実装では model_name にユースケース名が入っていた）
        elif log.model_name in ["OpenAIGpt", "OpenAIGptStreaming", "Gemini", "OpenAIDalle",
                                 "OpenAITextToSpeech", "OpenAISpeechToText", "OpenAIRag", "Riddle"]:
            log.use_case_type = log.model_name
        else:
            # それ以外はデフォルトで OpenAIGpt
            log.use_case_type = "OpenAIGpt"

        log.save()


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0007_rename_mode_name_to_is_riddle"),
    ]

    operations = [
        # まず use_case_type フィールドを追加（null=True で）
        migrations.AddField(
            model_name="chatlogs",
            name="use_case_type",
            field=models.CharField(
                choices=[
                    ("OpenAIGpt", "OpenAI GPT"),
                    ("OpenAIGptStreaming", "OpenAI GPT Streaming"),
                    ("Gemini", "Gemini"),
                    ("OpenAIDalle", "OpenAI Dall-e"),
                    ("OpenAITextToSpeech", "OpenAI Text to Speech"),
                    ("OpenAISpeechToText", "OpenAI Speech to Text"),
                    ("OpenAIRag", "OpenAI RAG"),
                    ("Riddle", "Riddle"),
                ],
                max_length=50,
                null=True,  # 一時的に null を許可
            ),
        ),
        # データ移行を実行
        migrations.RunPython(migrate_is_riddle_to_use_case_type, migrations.RunPython.noop),
        # is_riddle フィールドを削除
        migrations.RemoveField(
            model_name="chatlogs",
            name="is_riddle",
        ),
        # use_case_type のデフォルト値を設定し、null=False にする
        migrations.AlterField(
            model_name="chatlogs",
            name="use_case_type",
            field=models.CharField(
                choices=[
                    ("OpenAIGpt", "OpenAI GPT"),
                    ("OpenAIGptStreaming", "OpenAI GPT Streaming"),
                    ("Gemini", "Gemini"),
                    ("OpenAIDalle", "OpenAI Dall-e"),
                    ("OpenAITextToSpeech", "OpenAI Text to Speech"),
                    ("OpenAISpeechToText", "OpenAI Speech to Text"),
                    ("OpenAIRag", "OpenAI RAG"),
                    ("Riddle", "Riddle"),
                ],
                default="OpenAIGpt",
                max_length=50,
            ),
        ),
    ]
