# Generated by Django 6.0 on 2026-03-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0008_remove_chatlogs_is_riddle_chatlogs_use_case_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiddleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="問題文")),
                ("answer_text", models.TextField(verbose_name="正解")),
                ("order", models.IntegerField(default=0, verbose_name="出題順序")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "なぞなぞ問題",
                "verbose_name_plural": "なぞなぞ問題一覧",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
