# Generated by Django 6.0 on 2026-03-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0009_riddlequestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riddlequestion",
            name="question_text",
            field=models.CharField(max_length=255, unique=True, verbose_name="問題文"),
        ),
    ]
