# Generated by Django 6.0 on 2026-03-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0010_alter_riddlequestion_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riddlequestion",
            name="order",
            field=models.IntegerField(default=0, unique=True, verbose_name="出題順序"),
        ),
    ]
