# Generated by Django 6.0 on 2026-03-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0011_alter_riddlequestion_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="riddlequestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
