# Generated by Django 6.0 on 2026-03-15 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0012_riddlequestion_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riddlequestion",
            name="updated_at",
        ),
    ]
