# Generated by Django 6.0 on 2026-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0014_chatlogs_riddle_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatlogs",
            name="riddle_state",
        ),
        migrations.AddField(
            model_name="chatlogs",
            name="next_riddle_state",
            field=models.CharField(
                blank=True,
                help_text="なぞなぞセッションの状態管理用（ASK_QUESTION, WAIT_ANSWER, ...）",
                max_length=20,
                null=True,
            ),
        ),
    ]
