# Generated by Django 6.0 on 2026-03-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0015_remove_chatlogs_riddle_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlogs",
            name="next_riddle_state",
            field=models.CharField(
                blank=True,
                help_text="なぞなぞセッションの状態管理用（START, WAIT_ANSWER, ...）",
                max_length=100,
                null=True,
            ),
        ),
    ]
