# Generated by Django 6.0 on 2026-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0016_alter_chatlogs_next_riddle_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlogs",
            name="next_riddle_state",
            field=models.CharField(
                blank=True,
                default="",
                help_text="なぞなぞセッションの状態管理用（START, WAIT_ANSWER, ...）",
                max_length=100,
            ),
        ),
    ]
