# Generated by Django 6.0 on 2026-06-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0020_alter_chatlogs_use_case_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlogs",
            name="use_case_type",
            field=models.CharField(
                choices=[
                    ("OpenAIGpt", "OpenAI GPT"),
                    ("OpenAIGptStreaming", "OpenAI GPT Streaming"),
                    ("Gemini", "Gemini"),
                    ("OpenAIImage", "OpenAI Image Generation"),
                    ("OpenAITextToSpeech", "OpenAI Text to Speech"),
                    ("OpenAISpeechToText", "OpenAI Speech to Text"),
                    ("OpenAIRag", "OpenAI RAG"),
                    ("RokunoheMinutesRag", "Rokunohe Minutes RAG"),
                    ("Riddle", "Riddle"),
                ],
                default="OpenAIGpt",
                help_text="使用されたユースケースタイプ（例: OpenAIGpt, Riddle, OpenAIImage）",
                max_length=50,
            ),
        ),
    ]
