# Generated by Django 6.0 on 2026-06-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0021_alter_chatlogs_use_case_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RokunoheMinuteThemeAnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "実行中"),
                            ("completed", "完了"),
                            ("failed", "失敗"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="実行状態",
                    ),
                ),
                (
                    "requested_cluster_count",
                    models.PositiveIntegerField(
                        default=50, verbose_name="要求クラスタ数"
                    ),
                ),
                (
                    "actual_cluster_count",
                    models.PositiveIntegerField(default=0, verbose_name="実クラスタ数"),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="分析対象チャンク数"
                    ),
                ),
                (
                    "llm_model_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="LLMモデル名"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラーメッセージ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "六戸町会議録テーマ分析ジョブ",
                "verbose_name_plural": "六戸町会議録テーマ分析ジョブ一覧",
                "db_table": "llm_chat_rokunohe_minute_theme_analysis_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RokunoheMinuteThemeCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_index",
                    models.PositiveIntegerField(verbose_name="クラスタ番号"),
                ),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="代表テーマ名"),
                ),
                (
                    "representative_chunk_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="代表チャンクID"
                    ),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(default=0, verbose_name="チャンク数"),
                ),
                (
                    "character_count",
                    models.PositiveIntegerField(default=0, verbose_name="文字数"),
                ),
                (
                    "pdf_count",
                    models.PositiveIntegerField(default=0, verbose_name="PDF数"),
                ),
                (
                    "source_date_from",
                    models.CharField(blank=True, max_length=8, verbose_name="開始日"),
                ),
                (
                    "source_date_to",
                    models.CharField(blank=True, max_length=8, verbose_name="終了日"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clusters",
                        to="llm_chat.rokunoheminutethemeanalysisjob",
                        verbose_name="分析ジョブ",
                    ),
                ),
            ],
            options={
                "verbose_name": "六戸町会議録テーマクラスタ",
                "verbose_name_plural": "六戸町会議録テーマクラスタ一覧",
                "db_table": "llm_chat_rokunohe_minute_theme_cluster",
            },
        ),
        migrations.CreateModel(
            name="RokunoheMinuteThemeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_id",
                    models.CharField(max_length=255, verbose_name="チャンクID"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="出典PDF"
                    ),
                ),
                (
                    "source_date",
                    models.CharField(blank=True, max_length=8, verbose_name="出典日"),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ページ番号"
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="チャンク番号"
                    ),
                ),
                (
                    "candidate_labels",
                    models.JSONField(
                        blank=True, default=list, verbose_name="候補テーマラベル"
                    ),
                ),
                (
                    "character_count",
                    models.PositiveIntegerField(default=0, verbose_name="文字数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_chunks",
                        to="llm_chat.rokunoheminutethemeanalysisjob",
                        verbose_name="分析ジョブ",
                    ),
                ),
                (
                    "cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_chunks",
                        to="llm_chat.rokunoheminutethemecluster",
                        verbose_name="テーマクラスタ",
                    ),
                ),
            ],
            options={
                "verbose_name": "六戸町会議録テーマチャンク",
                "verbose_name_plural": "六戸町会議録テーマチャンク一覧",
                "db_table": "llm_chat_rokunohe_minute_theme_chunk",
            },
        ),
        migrations.AddIndex(
            model_name="rokunoheminutethemecluster",
            index=models.Index(
                fields=["job", "cluster_index"], name="llm_chat_ro_job_id_5360fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rokunoheminutethemecluster",
            unique_together={("job", "cluster_index")},
        ),
        migrations.AddIndex(
            model_name="rokunoheminutethemechunk",
            index=models.Index(
                fields=["job", "chunk_id"], name="llm_chat_ro_job_id_eeecb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rokunoheminutethemechunk",
            index=models.Index(
                fields=["cluster", "source_date"], name="llm_chat_ro_cluster_6cd324_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rokunoheminutethemechunk",
            unique_together={("job", "chunk_id")},
        ),
    ]
