# Generated by Django 6.0 on 2026-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0022_rokunoheminutethemeanalysisjob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rokunoheminutethemechunk",
            name="chunk_id",
            field=models.CharField(max_length=512, verbose_name="チャンクID"),
        ),
        migrations.AlterField(
            model_name="rokunoheminutethemechunk",
            name="source",
            field=models.CharField(blank=True, max_length=512, verbose_name="出典PDF"),
        ),
        migrations.AlterField(
            model_name="rokunoheminutethemecluster",
            name="representative_chunk_id",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="代表チャンクID"
            ),
        ),
    ]
