# Generated by Django 6.0 on 2026-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0023_alter_rokunoheminutethemechunk_chunk_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rokunoheminutethemechunk",
            name="chunk_id",
            field=models.CharField(
                db_collation="utf8mb4_bin", max_length=512, verbose_name="チャンクID"
            ),
        ),
    ]
