# Generated by Django 6.0 on 2026-06-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0024_alter_rokunoheminutethemechunk_chunk_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rokunoheminutethemechunk",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="rokunoheminutethemechunk",
            name="llm_chat_ro_job_id_eeecb5_idx",
        ),
        migrations.RemoveIndex(
            model_name="rokunoheminutethemechunk",
            name="llm_chat_ro_cluster_6cd324_idx",
        ),
        migrations.AlterUniqueTogether(
            name="rokunoheminutethemecluster",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="rokunoheminutethemecluster",
            name="llm_chat_ro_job_id_5360fe_idx",
        ),
        migrations.RemoveField(
            model_name="rokunoheminutethemecluster",
            name="job",
        ),
        migrations.DeleteModel(
            name="RokunoheMinuteThemeChunk",
        ),
        migrations.DeleteModel(
            name="RokunoheMinuteThemeAnalysisJob",
        ),
        migrations.DeleteModel(
            name="RokunoheMinuteThemeCluster",
        ),
    ]
