# Generated by Django 6.0 on 2026-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0025_alter_rokunoheminutethemechunk_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIRagPdf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="llm_chat/openai_rag_pdfs/",
                        verbose_name="PDFファイル",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vector DB登録日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "OpenAI RAG PDF",
                "verbose_name_plural": "OpenAI RAG PDF一覧",
                "ordering": ["-created_at"],
            },
        ),
    ]
