# Generated by Django 6.0 on 2026-06-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0026_openairagpdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openairagpdf",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="llm_chat/openai_rag_pdfs/",
                verbose_name="PDFファイル",
            ),
        ),
    ]
