# Generated by Django 6.0 on 2026-06-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("llm_chat", "0027_alter_openairagpdf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="openairagpdf",
            name="file",
        ),
    ]
