# Generated by Django 5.2.4 on 2025-11-06 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_cur_code", models.CharField(max_length=3)),
                ("dest_cur_code", models.CharField(max_length=3)),
                ("rate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FaoFoodBalanceRankers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("rank", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("item", models.CharField(max_length=255)),
                ("element", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=255)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50)),
                ("url_file_name", models.CharField(max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VietnamStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element", models.CharField(max_length=255)),
                ("period", models.DateField()),
                ("value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("note", models.TextField(verbose_name="投稿内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="公開日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry1", models.CharField(max_length=10)),
                ("industry2", models.CharField(max_length=20)),
                ("industry_class", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "unique_together": {("industry1", "industry2")},
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "ind_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vietnam_research.indclass",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vietnam_research.market",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sbi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vietnam_research.symbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_date", models.DateField()),
                ("open_price", models.FloatField(null=True)),
                ("high_price", models.FloatField(null=True)),
                ("low_price", models.FloatField(null=True)),
                ("closing_price", models.FloatField(null=True)),
                ("volume", models.FloatField(null=True)),
                ("marketcap", models.FloatField(null=True)),
                ("per", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vietnam_research.symbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialResultWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_date", models.DateField()),
                ("quarter", models.SmallIntegerField()),
                ("eps_ok", models.BooleanField(null=True)),
                ("sales_ok", models.BooleanField(null=True)),
                ("guidance_ok", models.BooleanField(null=True)),
                ("eps_estimate", models.FloatField()),
                ("eps_actual", models.FloatField()),
                ("sales_estimate", models.FloatField()),
                ("sales_actual", models.FloatField()),
                ("y_over_y_growth_rate", models.FloatField()),
                ("note_url", models.URLField(null=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vietnam_research.symbol",
                    ),
                ),
                (
                    "eps_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="r_eps_unit",
                        to="vietnam_research.unit",
                    ),
                ),
                (
                    "sales_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="r_sales_unit",
                        to="vietnam_research.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Uptrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stocks_price_oldest", models.FloatField()),
                ("stocks_price_latest", models.FloatField()),
                ("stocks_price_delta", models.FloatField()),
                (
                    "symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vietnam_research.symbol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VnIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Y", models.CharField(max_length=4)),
                ("M", models.CharField(max_length=2)),
                ("closing_price", models.FloatField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("Y", "M"), name="y_m_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("already_has", models.BooleanField(blank=True, default=1, null=True)),
                ("bought_day", models.DateField(blank=True, null=True)),
                (
                    "stocks_price",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("stocks_count", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vietnam_research.symbol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "articles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vietnam_research.articles",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("articles_id", "user_id"), name="articles_user_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="symbol",
            constraint=models.UniqueConstraint(
                fields=("code", "market_id"), name="code_market_id_unique"
            ),
        ),
    ]
