# Generated by Django 6.0 on 2026-03-28 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vietnam_research", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialresultwatch",
            name="eps_actual",
            field=models.FloatField(verbose_name="EPS実績"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="eps_estimate",
            field=models.FloatField(verbose_name="EPS予想"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="eps_ok",
            field=models.BooleanField(null=True, verbose_name="EPS達成"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="eps_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r_eps_unit",
                to="vietnam_research.unit",
                verbose_name="EPS単位",
            ),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="guidance_ok",
            field=models.BooleanField(null=True, verbose_name="ガイダンス達成"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="note_url",
            field=models.URLField(blank=True, null=True, verbose_name="NoteURL"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="quarter",
            field=models.SmallIntegerField(verbose_name="四半期"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="recorded_date",
            field=models.DateField(verbose_name="Note公開日"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="sales_actual",
            field=models.FloatField(verbose_name="売上実績"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="sales_estimate",
            field=models.FloatField(verbose_name="売上予想"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="sales_ok",
            field=models.BooleanField(null=True, verbose_name="売上達成"),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="sales_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r_sales_unit",
                to="vietnam_research.unit",
                verbose_name="売上単位",
            ),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="symbol",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vietnam_research.symbol",
                verbose_name="シンボル",
            ),
        ),
        migrations.AlterField(
            model_name="financialresultwatch",
            name="y_over_y_growth_rate",
            field=models.FloatField(verbose_name="前年同期比(%)"),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="already_has",
            field=models.BooleanField(
                blank=True, default=1, null=True, verbose_name="保有済み"
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="bought_day",
            field=models.DateField(blank=True, null=True, verbose_name="購入日"),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="stocks_count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="数量"
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="stocks_price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="購入価格"
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="symbol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vietnam_research.symbol",
                verbose_name="シンボル",
            ),
        ),
        migrations.AddConstraint(
            model_name="watchlist",
            constraint=models.UniqueConstraint(
                fields=("user", "symbol"), name="user_symbol_unique"
            ),
        ),
    ]
