# Generated by Django 5.1 on 2024-12-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vietnam_research", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="industry",
            name="trade_price_of_a_day",
        ),
    ]
