# Generated by Django 5.1 on 2024-12-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vietnam_research", "0002_remove_industry_trade_price_of_a_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="closing_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="high_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="low_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="marketcap",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="open_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="per",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="volume",
            field=models.FloatField(null=True),
        ),
    ]
