# Generated by Django 6.0 on 2026-03-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vietnam_research", "0002_alter_financialresultwatch_eps_actual_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialresultwatch",
            name="eps_unit",
        ),
        migrations.RemoveField(
            model_name="financialresultwatch",
            name="sales_unit",
        ),
        migrations.RemoveField(
            model_name="financialresultwatch",
            name="symbol",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
        migrations.DeleteModel(
            name="FinancialResultWatch",
        ),
    ]
