# Generated by Django 6.0 on 2026-03-31 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa_research", "0012_alter_financialresultwatch_ticker_and_more"),
        ("vietnam_research", "0003_remove_financialresultwatch_eps_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SbiUsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usa_research.symbol",
                    ),
                ),
            ],
        ),
    ]
