# Generated by Django 6.0 on 2026-03-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vietnam_research", "0004_sbiusa"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SbiUsa",
        ),
    ]
