# Generated by Django 5.1 on 2025-01-12 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "thinking_type",
                    models.CharField(
                        choices=[
                            ("google_maps_based", "Google Mapsレビューに基づく"),
                            ("rag_based", "RAGベースの推論"),
                            ("ng_word_based", "NGワードに基づく制限"),
                        ],
                        default="google_maps_based",
                        max_length=50,
                    ),
                ),
                ("forbidden_keywords", models.TextField(blank=True, null=True)),
                ("vector", models.BinaryField(blank=True, null=True)),
                ("speed", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="GooglemapsReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("review_text", models.TextField()),
                ("rating", models.FloatField()),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("review_date", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("vector", models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActionTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_turn", models.FloatField(default=0)),
                ("can_act", models.BooleanField(default=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_agent.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acted_at_turn", models.IntegerField()),
                ("done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_agent.entity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_agent.entity",
                    ),
                ),
            ],
        ),
    ]
