# Generated by Django 5.2.4 on 2025-07-09 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="forbidden_keywords",
        ),
        migrations.AlterField(
            model_name="entity",
            name="thinking_type",
            field=models.CharField(
                choices=[
                    ("google_maps_based", "Google Mapsレビューに基づく"),
                    ("rag_based", "RAGベースの推論"),
                    ("ng_word_based", "NGワードに基づく制限"),
                    ("openai_assistant", "OpenAI会話エージェント"),
                    ("openai_assistant_strict", "OpenAI会話エージェント（厳格モード）"),
                ],
                default="google_maps_based",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="GuardrailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forbidden_words",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="禁止ワードのリスト（JSON形式）",
                    ),
                ),
                (
                    "max_input_length",
                    models.IntegerField(default=500, help_text="入力文字数の上限"),
                ),
                (
                    "use_openai_moderation",
                    models.BooleanField(
                        default=True, help_text="OpenAI Moderation APIを使用するか"
                    ),
                ),
                (
                    "strict_mode",
                    models.BooleanField(
                        default=False, help_text="厳格モード（エラー時もブロック）"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_agent.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "ガードレール設定",
                "verbose_name_plural": "ガードレール設定",
            },
        ),
    ]
