# Generated by Django 5.1 on 2025-01-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="speed",
            field=models.IntegerField(default=10),
        ),
    ]
