# Generated by Django 5.1 on 2025-01-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversationhistory",
            options={},
        ),
        migrations.AlterModelTable(
            name="conversationhistory",
            table=None,
        ),
    ]
