# Generated by Django 6.0.7 on 2026-08-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionhistory",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="guardrailconfig",
            name="entity",
        ),
        migrations.RemoveField(
            model_name="message",
            name="entity",
        ),
        migrations.DeleteModel(
            name="RagMaterial",
        ),
        migrations.DeleteModel(
            name="ActionHistory",
        ),
        migrations.DeleteModel(
            name="GuardrailConfig",
        ),
        migrations.DeleteModel(
            name="Entity",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
