# Generated by Django 5.2.4 on 2025-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0002_remove_entity_forbidden_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardrailconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
