# Generated by Django 5.1 on 2025-01-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0002_alter_conversationhistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterModelTable(
            name="entity",
            table=None,
        ),
        migrations.AlterModelTable(
            name="message",
            table=None,
        ),
        migrations.AlterModelTable(
            name="review",
            table=None,
        ),
    ]
