# Generated by Django 5.1 on 2025-01-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_agent", "0003_alter_message_options_alter_review_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review",
            new_name="GooglemapsReview",
        ),
    ]
