# Generated by Django 5.1 on 2025-01-11 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0003_actiontimeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontimeline",
            name="can_act",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ActionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acted_at_turn", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_agent.entity",
                    ),
                ),
            ],
        ),
    ]
