# Generated by Django 5.1 on 2025-01-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0004_actiontimeline_can_act_actionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="thinking_type",
            field=models.CharField(
                choices=[
                    ("google_maps_based", "Google Mapsレビューに基づく"),
                    ("rag_based", "RAGベースの推論"),
                    ("ng_word_based", "NGワードに基づく制限"),
                ],
                default="google_maps_based",
                max_length=50,
            ),
        ),
    ]
