# Generated by Django 5.1 on 2025-01-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0005_entity_thinking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionhistory",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
