# Generated by Django 5.1 on 2025-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_agent", "0006_actionhistory_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionhistory",
            name="acted_at_turn",
            field=models.IntegerField(),
        ),
    ]
