# Generated by Django 5.1 on 2024-10-04 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="エリア"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="選挙名"
                    ),
                ),
                ("execution_date", models.DateField(verbose_name="執行日")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VotePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VoteStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(max_length=10, unique=True, verbose_name="略称"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="病棟名")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="病棟種"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CitySector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="市区")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hospital.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="住所")),
                ("date_of_birth", models.DateField(verbose_name="生年月日")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectionLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "billing_method",
                    models.CharField(
                        blank=True,
                        choices=[(1, "代理・直接"), (2, "代理・郵便")],
                        max_length=5,
                        null=True,
                        verbose_name="投票用紙請求の方法",
                    ),
                ),
                (
                    "proxy_billing_request_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="代理請求の依頼を受けた日"
                    ),
                ),
                (
                    "proxy_billing_date",
                    models.DateField(blank=True, null=True, verbose_name="代理請求日"),
                ),
                (
                    "ballot_received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="投票用紙受領日"
                    ),
                ),
                (
                    "vote_date",
                    models.DateField(blank=True, null=True, verbose_name="投票日"),
                ),
                (
                    "whether_to_apply_for_proxy_voting",
                    models.CharField(
                        blank=True,
                        choices=[(1, "無"), (2, "有")],
                        max_length=1,
                        null=True,
                        verbose_name="代理投票申請の有無",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="投票用紙送付日"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="取込日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.election",
                    ),
                ),
                (
                    "vote_city_sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.citysector",
                        verbose_name="投票区",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="選挙人氏名",
                    ),
                ),
                (
                    "voter_witness",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_witness",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="投票立会人",
                    ),
                ),
                (
                    "vote_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.voteplace",
                        verbose_name="投票場所",
                    ),
                ),
                (
                    "vote_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.votestatus",
                    ),
                ),
                (
                    "vote_ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.ward",
                        verbose_name="病棟",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ward",
            name="ward_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hospital.wardtype",
                verbose_name="病棟種",
            ),
        ),
    ]
