# Generated by Django 6.0 on 2026-03-25 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userattribute",
            name="member",
        ),
        migrations.AlterField(
            model_name="electionledger",
            name="voter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voter",
                to=settings.AUTH_USER_MODEL,
                verbose_name="選挙人氏名",
            ),
        ),
        migrations.AlterField(
            model_name="electionledger",
            name="vote_observer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voter_witness",
                to=settings.AUTH_USER_MODEL,
                verbose_name="投票立会人",
            ),
        ),
        migrations.AddField(
            model_name="userattribute",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userattribute",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="備考"),
        ),
        migrations.AddField(
            model_name="userattribute",
            name="role",
            field=models.CharField(
                choices=[("staff", "病院スタッフ"), ("patient", "患者")],
                max_length=20,
                null=True,
                verbose_name="ロール",
            ),
        ),
        migrations.AddField(
            model_name="userattribute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="userattribute",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userAttribute",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザ",
            ),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="address",
            field=models.TextField(null=True, verbose_name="住所"),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="生年月日"),
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
