# Generated by Django 5.1 on 2024-11-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electionledger",
            name="vote_status",
        ),
        migrations.RemoveField(
            model_name="electionledger",
            name="whether_to_apply_for_proxy_voting",
        ),
        migrations.AddField(
            model_name="electionledger",
            name="applied_for_proxy_voting",
            field=models.BooleanField(default=False, verbose_name="代理投票申請の有無"),
        ),
        migrations.DeleteModel(
            name="VoteStatus",
        ),
    ]
