# Generated by Django 6.0 on 2026-03-25 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_merge_member_to_userattribute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattribute",
            name="address",
            field=models.TextField(verbose_name="住所"),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="date_of_birth",
            field=models.DateField(verbose_name="生年月日"),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="role",
            field=models.CharField(
                choices=[("staff", "病院スタッフ"), ("patient", "患者")],
                max_length=20,
                verbose_name="ロール",
            ),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userAttribute",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザ",
            ),
        ),
    ]
