# Generated by Django 5.1 on 2024-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_rename_voter_witness_electionledger_vote_observer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electionledger",
            name="billing_method",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "代理・直接"), (2, "代理・郵便")],
                null=True,
                verbose_name="投票用紙請求の方法",
            ),
        ),
    ]
