# Generated by Django 5.1 on 2024-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignageMenuName",
            fields=[
                (
                    "menu_code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("menu_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StoreInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.IntegerField()),
                ("searchword", models.CharField(blank=True, max_length=100, null=True)),
                ("place_id", models.CharField(blank=True, max_length=200, null=True)),
                ("shop_name", models.CharField(max_length=200)),
                ("shop_latlng", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
