# Generated by Django 5.1 on 2025-01-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NearbyPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.IntegerField()),
                (
                    "search_types",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("place_id", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
