# Generated by Django 5.1 on 2025-01-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmarker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_id", models.CharField(max_length=200, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="nearbyplace",
            name="location",
        ),
        migrations.RemoveField(
            model_name="nearbyplace",
            name="name",
        ),
        migrations.RemoveField(
            model_name="nearbyplace",
            name="place_id",
        ),
        migrations.RemoveField(
            model_name="nearbyplace",
            name="rating",
        ),
        migrations.AddField(
            model_name="nearbyplace",
            name="place",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="gmarker.place",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PlaceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True)),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("publish_time", models.DateTimeField(blank=True, null=True)),
                ("google_maps_uri", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gmarker.place"
                    ),
                ),
            ],
        ),
    ]
