# Generated by Django 5.1 on 2024-12-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmarker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearbyPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (1, "Category"),
                            (2, "Pin Select"),
                            (3, "Database Insert"),
                            (9, "Default Location"),
                        ]
                    ),
                ),
                (
                    "search_word",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("place_id", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="SignageMenuName",
            new_name="CategorySearchMaster",
        ),
        migrations.DeleteModel(
            name="StoreInformation",
        ),
        migrations.RenameField(
            model_name="categorysearchmaster",
            old_name="menu_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="categorysearchmaster",
            old_name="menu_name",
            new_name="name",
        ),
    ]
