# Generated by Django 5.1 on 2024-12-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmarker", "0002_nearbyplace_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategorySearchMaster",
        ),
    ]
