# Generated by Django 5.1 on 2025-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmarker", "0002_place_remove_nearbyplace_location_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="placereview",
            constraint=models.UniqueConstraint(
                fields=("place", "author"), name="unique_place_author"
            ),
        ),
    ]
