# Generated by Django 5.1 on 2024-12-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmarker", "0003_delete_categorysearchmaster"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nearbyplace",
            old_name="search_word",
            new_name="search_types",
        ),
    ]
