# Generated by Django 5.1 on 2025-01-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmarker", "0004_rename_search_word_nearbyplace_search_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="nearbyplace",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nearbyplace",
            name="category",
            field=models.IntegerField(),
        ),
    ]
