# Generated by Django 5.1 on 2025-01-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gmarker", "0005_nearbyplace_rating_alter_nearbyplace_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField()),
                ("author", models.CharField(max_length=200)),
                ("publish_time", models.DateTimeField()),
                ("google_maps_uri", models.URLField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="gmarker.nearbyplace",
                    ),
                ),
            ],
        ),
    ]
