# Generated by Django 5.1 on 2025-01-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gmarker", "0006_placereview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PlaceReview",
        ),
    ]
