# Generated by Django 5.1 on 2025-03-26 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CultivationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="JmaArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="JmaWeatherCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("summary_code", models.CharField(max_length=3)),
                ("image", models.CharField(max_length=7)),
                ("name", models.CharField(max_length=20)),
                ("name_en", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RouteSuggestImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("coord", models.CharField(max_length=256)),
                ("ordering", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SamplingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("times", models.IntegerField()),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoilHardnessMeasurementImportErrors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.CharField(max_length=256)),
                ("folder", models.CharField(max_length=256)),
                ("message", models.TextField()),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.companycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JmaPrefecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "jma_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmaarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JmaRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "jma_prefecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmaprefecture",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JmaCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=7, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "jma_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmaregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JmaAmedas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                (
                    "jma_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmaregion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("center", models.CharField(max_length=256)),
                ("area", models.FloatField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="land/")),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.company",
                    ),
                ),
                (
                    "cultivation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.cultivationtype",
                    ),
                ),
                (
                    "jma_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmacity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="name_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="LandPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("name", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "name"), name="year_name_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LandLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sampling_date", models.DateField()),
                ("analysis_request_date", models.DateField(null=True)),
                ("reporting_date", models.DateField(null=True)),
                ("analysis_number", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "analytical_agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.company",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.crop",
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.land",
                    ),
                ),
                (
                    "sampling_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "land_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landperiod",
                    ),
                ),
                (
                    "sampling_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.samplingmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandScoreChemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ec", models.FloatField(null=True)),
                ("nh4n", models.FloatField(null=True)),
                ("no3n", models.FloatField(null=True)),
                ("total_nitrogen", models.FloatField(null=True)),
                ("nh4_per_nitrogen", models.FloatField(null=True)),
                ("ph", models.FloatField(null=True)),
                ("cao", models.FloatField(null=True)),
                ("mgo", models.FloatField(null=True)),
                ("k2o", models.FloatField(null=True)),
                ("base_saturation", models.FloatField(null=True)),
                ("cao_per_mgo", models.FloatField(null=True)),
                ("mgo_per_k2o", models.FloatField(null=True)),
                ("phosphorus_absorption", models.FloatField(null=True)),
                ("p2o5", models.FloatField(null=True)),
                ("cec", models.FloatField(null=True)),
                ("humus", models.FloatField(null=True)),
                ("bulk_density", models.FloatField(null=True)),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "land_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landblock",
                    ),
                ),
                (
                    "land_ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landledger",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SamplingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.IntegerField()),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "land_block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landblock",
                    ),
                ),
                (
                    "sampling_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.samplingmethod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SoilHardnessMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_memory", models.IntegerField()),
                ("set_datetime", models.DateTimeField()),
                ("set_depth", models.IntegerField()),
                ("set_spring", models.IntegerField()),
                ("set_cone", models.IntegerField()),
                ("depth", models.IntegerField()),
                ("pressure", models.IntegerField()),
                ("folder", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "land_block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landblock",
                    ),
                ),
                (
                    "land_ledger",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landledger",
                    ),
                ),
                (
                    "set_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JmaWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warnings", models.CharField(max_length=100)),
                (
                    "jma_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmaregion",
                    ),
                ),
            ],
            options={
                "unique_together": {("jma_region",)},
            },
        ),
        migrations.CreateModel(
            name="JmaWeather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporting_date", models.DateField()),
                ("weather_text", models.CharField(max_length=255)),
                ("wind_text", models.CharField(max_length=255)),
                ("wave_text", models.CharField(max_length=255)),
                ("avg_rain_probability", models.FloatField(null=True)),
                ("avg_min_temperature", models.FloatField(null=True)),
                ("avg_max_temperature", models.FloatField(null=True)),
                ("avg_max_wind_speed", models.FloatField(null=True)),
                (
                    "jma_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmaregion",
                    ),
                ),
                (
                    "jma_weather_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.jmaweathercode",
                    ),
                ),
            ],
            options={
                "unique_together": {("jma_region", "reporting_date")},
            },
        ),
        migrations.CreateModel(
            name="LandReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "land_ledger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landledger",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("land_ledger",), name="land_ledger_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="landledger",
            constraint=models.UniqueConstraint(
                fields=("land", "land_period"), name="land_period_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="soilhardnessmeasurement",
            constraint=models.UniqueConstraint(
                fields=("set_device", "set_memory", "set_datetime", "depth"),
                name="device_memory_datetime_depth_unique",
            ),
        ),
    ]
