# Generated by Django 5.1 on 2024-12-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="jmawarning",
            unique_together={("jma_region",)},
        ),
        migrations.AlterUniqueTogether(
            name="jmaweather",
            unique_together={("jma_region", "reporting_date")},
        ),
    ]
