# Generated by Django 6.0 on 2026-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0002_userattribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="RokunoheLandRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ledger_type",
                    models.CharField(max_length=100, verbose_name="帳簿種別"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="住所")),
                ("coordinate", models.CharField(max_length=100, verbose_name="座標")),
                (
                    "registered_land_category",
                    models.CharField(max_length=50, verbose_name="登記地目"),
                ),
                (
                    "current_land_category",
                    models.CharField(max_length=50, verbose_name="現況地目"),
                ),
                (
                    "registered_area",
                    models.CharField(max_length=50, verbose_name="登記面積"),
                ),
                (
                    "current_area",
                    models.CharField(max_length=50, verbose_name="現況面積"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="備考"),
                ),
            ],
            options={
                "verbose_name": "六戸登記簿",
                "verbose_name_plural": "六戸登記簿",
                "db_table": "r_rokunohe_land_registry",
            },
        ),
    ]
