# Generated by Django 6.0 on 2026-05-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0003_rokunohelandregistry"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rokunohelandregistry",
            table="rokunohe_land_registry",
        ),
    ]
