# Generated by Django 6.0 on 2026-05-14 12:48

import re

from django.db import migrations, models


def normalize_area_text(apps, schema_editor):
    model = apps.get_model("soil_analysis", "RokunoheLandRegistry")
    for row in model.objects.all():
        reg_digits = re.sub(r"[^\d]", "", row.registered_area or "")
        cur_digits = re.sub(r"[^\d]", "", row.current_area or "")
        row.registered_area = reg_digits or "0"
        row.current_area = cur_digits or "0"
        row.save(update_fields=["registered_area", "current_area"])


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0004_alter_rokunohelandregistry_table"),
    ]

    operations = [
        migrations.RunPython(normalize_area_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="rokunohelandregistry",
            name="current_area",
            field=models.PositiveIntegerField(verbose_name="現況面積(㎡)"),
        ),
        migrations.AlterField(
            model_name="rokunohelandregistry",
            name="registered_area",
            field=models.PositiveIntegerField(verbose_name="登記面積(㎡)"),
        ),
    ]
