# Generated by Django 6.0 on 2026-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0005_alter_rokunohelandregistry_current_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landscorechemical",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
