# Generated by Django 6.0 on 2026-05-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0008_create_chemical_import_errors"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilChemicalAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ec", models.FloatField(null=True)),
                ("nh4n", models.FloatField(null=True)),
                ("no3n", models.FloatField(null=True)),
                ("total_nitrogen", models.FloatField(null=True)),
                ("nh4_per_nitrogen", models.FloatField(null=True)),
                ("ph", models.FloatField(null=True)),
                ("cao", models.FloatField(null=True)),
                ("mgo", models.FloatField(null=True)),
                ("k2o", models.FloatField(null=True)),
                ("base_saturation", models.FloatField(null=True)),
                ("cao_per_mgo", models.FloatField(null=True)),
                ("mgo_per_k2o", models.FloatField(null=True)),
                ("phosphorus_absorption", models.FloatField(null=True)),
                ("p2o5", models.FloatField(null=True)),
                ("cec", models.FloatField(null=True)),
                ("humus", models.FloatField(null=True)),
                ("bulk_density", models.FloatField(null=True)),
                ("source_agency", models.CharField(max_length=256, null=True)),
                ("source_file", models.CharField(max_length=256, null=True)),
                ("remark", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "land_ledger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.landledger",
                    ),
                ),
            ],
        ),
    ]
