# Generated by Django 6.0 on 2026-05-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0009_soilchemicalanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="soilchemicalanalysis",
            name="lime_saturation",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="soilchemicalanalysis",
            name="magnesia_saturation",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="soilchemicalanalysis",
            name="potash_saturation",
            field=models.FloatField(null=True),
        ),
    ]
