# Generated by Django 6.0 on 2026-05-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0010_soilchemicalanalysis_lime_saturation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soilchemicalmeasurement",
            name="land_block",
        ),
        migrations.AddField(
            model_name="soilchemicalmeasurement",
            name="lime_saturation",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="soilchemicalmeasurement",
            name="magnesia_saturation",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="soilchemicalmeasurement",
            name="potash_saturation",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="soilchemicalmeasurement",
            name="source_agency",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="soilchemicalmeasurement",
            name="source_file",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="land_ledger",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.landledger",
            ),
        ),
        migrations.DeleteModel(
            name="SoilChemicalAnalysis",
        ),
    ]
