# Generated by Django 6.0 on 2026-05-30 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0011_remove_soilchemicalmeasurement_land_block_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soilchemicalmeasurement",
            name="source_agency",
        ),
    ]
