# Generated by Django 6.0 on 2026-05-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0012_remove_soilchemicalmeasurement_source_agency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soilchemicalmeasurement",
            name="remark",
        ),
    ]
