# Generated by Django 6.0 on 2026-05-30 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0014_alter_company_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="area",
            field=models.FloatField(blank=True, null=True, verbose_name="面積"),
        ),
        migrations.AlterField(
            model_name="land",
            name="center",
            field=models.CharField(max_length=256, verbose_name="中心座標"),
        ),
        migrations.AlterField(
            model_name="land",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.company",
                verbose_name="所属法人",
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="land",
            name="cultivation_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.cultivationtype",
                verbose_name="作型",
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="land/", verbose_name="画像"
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="jma_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmacity",
                verbose_name="市区町村(気象庁分類)",
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="name",
            field=models.CharField(max_length=256, verbose_name="圃場名"),
        ),
        migrations.AlterField(
            model_name="land",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="オーナー",
            ),
        ),
        migrations.AlterField(
            model_name="land",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="land",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="analysis_number",
            field=models.IntegerField(null=True, verbose_name="分析番号"),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="analysis_request_date",
            field=models.DateField(null=True, verbose_name="分析依頼日"),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="analytical_agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.company",
                verbose_name="分析機関",
            ),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="crop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.crop",
                verbose_name="作物",
            ),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="land",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.land",
                verbose_name="圃場",
            ),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="land_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.landperiod",
                verbose_name="時期",
            ),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="reporting_date",
            field=models.DateField(null=True, verbose_name="報告日"),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="sampling_date",
            field=models.DateField(verbose_name="採土日"),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="sampling_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.samplingmethod",
                verbose_name="採土法",
            ),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="sampling_staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="採土スタッフ",
            ),
        ),
        migrations.AlterField(
            model_name="landledger",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="base_saturation",
            field=models.FloatField(null=True, verbose_name="塩基飽和度"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="bulk_density",
            field=models.FloatField(null=True, verbose_name="仮比重"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="cao",
            field=models.FloatField(null=True, verbose_name="交換性石灰"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="cao_per_mgo",
            field=models.FloatField(null=True, verbose_name="CaO/MgO"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="cec",
            field=models.FloatField(null=True, verbose_name="塩基置換容量"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="ec",
            field=models.FloatField(null=True, verbose_name="電気伝導率"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="humus",
            field=models.FloatField(null=True, verbose_name="腐植"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="k2o",
            field=models.FloatField(null=True, verbose_name="交換性加里"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="land_ledger",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.landledger",
                verbose_name="台帳",
            ),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="lime_saturation",
            field=models.FloatField(null=True, verbose_name="石灰飽和度"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="magnesia_saturation",
            field=models.FloatField(null=True, verbose_name="苦土飽和度"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="mgo",
            field=models.FloatField(null=True, verbose_name="交換性苦土"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="mgo_per_k2o",
            field=models.FloatField(null=True, verbose_name="MgO/K2O"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="nh4_per_nitrogen",
            field=models.FloatField(null=True, verbose_name="アンモニア態窒素比"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="nh4n",
            field=models.FloatField(null=True, verbose_name="アンモニア態窒素"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="no3n",
            field=models.FloatField(null=True, verbose_name="硝酸態窒素"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="p2o5",
            field=models.FloatField(null=True, verbose_name="可給態リン酸"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="ph",
            field=models.FloatField(null=True, verbose_name="水素イオン濃度"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="phosphorus_absorption",
            field=models.FloatField(null=True, verbose_name="リン酸吸収係数"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="potash_saturation",
            field=models.FloatField(null=True, verbose_name="加里飽和度"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="source_file",
            field=models.CharField(
                max_length=256, null=True, verbose_name="データ元ファイル"
            ),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="total_nitrogen",
            field=models.FloatField(null=True, verbose_name="無機態窒素"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
