# Generated by Django 6.0 on 2026-05-30 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "soil_analysis",
            "0015_alter_land_area_alter_land_center_alter_land_company_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.companycategory",
                verbose_name="カテゴリ",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="company/", verbose_name="画像"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=256, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="company",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="companycategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="companycategory",
            name="name",
            field=models.CharField(max_length=256, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="companycategory",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="companycategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="crop",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="crop",
            name="name",
            field=models.CharField(max_length=256, verbose_name="作物名"),
        ),
        migrations.AlterField(
            model_name="crop",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="crop",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="cultivationtype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="cultivationtype",
            name="name",
            field=models.CharField(max_length=256, verbose_name="作型の名前"),
        ),
        migrations.AlterField(
            model_name="cultivationtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=256, verbose_name="デバイス名"),
        ),
        migrations.AlterField(
            model_name="device",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="jmaamedas",
            name="code",
            field=models.CharField(
                max_length=5, unique=True, verbose_name="アメダス観測所コード"
            ),
        ),
        migrations.AlterField(
            model_name="jmaamedas",
            name="jma_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmaregion",
                verbose_name="リージョン",
            ),
        ),
        migrations.AlterField(
            model_name="jmaarea",
            name="code",
            field=models.CharField(
                max_length=6, unique=True, verbose_name="エリアコード"
            ),
        ),
        migrations.AlterField(
            model_name="jmaarea",
            name="name",
            field=models.CharField(max_length=100, verbose_name="エリア名"),
        ),
        migrations.AlterField(
            model_name="jmacity",
            name="code",
            field=models.CharField(
                max_length=7, unique=True, verbose_name="市区町村コード"
            ),
        ),
        migrations.AlterField(
            model_name="jmacity",
            name="jma_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmaregion",
                verbose_name="リージョン",
            ),
        ),
        migrations.AlterField(
            model_name="jmacity",
            name="name",
            field=models.CharField(max_length=100, verbose_name="市区町村名"),
        ),
        migrations.AlterField(
            model_name="jmaprefecture",
            name="code",
            field=models.CharField(
                max_length=6, unique=True, verbose_name="都道府県コード"
            ),
        ),
        migrations.AlterField(
            model_name="jmaprefecture",
            name="jma_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmaarea",
                verbose_name="JMAエリア",
            ),
        ),
        migrations.AlterField(
            model_name="jmaprefecture",
            name="name",
            field=models.CharField(max_length=100, verbose_name="都道府県名"),
        ),
        migrations.AlterField(
            model_name="jmaregion",
            name="code",
            field=models.CharField(
                max_length=6, unique=True, verbose_name="リージョンコード"
            ),
        ),
        migrations.AlterField(
            model_name="jmaregion",
            name="jma_prefecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmaprefecture",
                verbose_name="都道府県",
            ),
        ),
        migrations.AlterField(
            model_name="jmaregion",
            name="name",
            field=models.CharField(max_length=100, verbose_name="リージョン名"),
        ),
        migrations.AlterField(
            model_name="jmawarning",
            name="jma_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmaregion",
                verbose_name="リージョン",
            ),
        ),
        migrations.AlterField(
            model_name="jmawarning",
            name="warnings",
            field=models.CharField(max_length=100, verbose_name="警報・注意報内容"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="avg_max_temperature",
            field=models.FloatField(null=True, verbose_name="最高気温"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="avg_max_wind_speed",
            field=models.FloatField(null=True, verbose_name="最大風速"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="avg_min_temperature",
            field=models.FloatField(null=True, verbose_name="最低気温"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="avg_rain_probability",
            field=models.FloatField(null=True, verbose_name="降水確率"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="jma_region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmaregion",
                verbose_name="リージョン",
            ),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="jma_weather_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.jmaweathercode",
                verbose_name="天気コード",
            ),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="reporting_date",
            field=models.DateField(verbose_name="報告日"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="wave_text",
            field=models.CharField(max_length=255, verbose_name="波の概況"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="weather_text",
            field=models.CharField(max_length=255, verbose_name="天気概況"),
        ),
        migrations.AlterField(
            model_name="jmaweather",
            name="wind_text",
            field=models.CharField(max_length=255, verbose_name="風の概況"),
        ),
        migrations.AlterField(
            model_name="jmaweathercode",
            name="code",
            field=models.CharField(
                max_length=3, unique=True, verbose_name="天気コード"
            ),
        ),
        migrations.AlterField(
            model_name="jmaweathercode",
            name="image",
            field=models.CharField(max_length=7, verbose_name="画像ファイル名"),
        ),
        migrations.AlterField(
            model_name="jmaweathercode",
            name="name",
            field=models.CharField(max_length=20, verbose_name="天気名（日本語）"),
        ),
        migrations.AlterField(
            model_name="jmaweathercode",
            name="name_en",
            field=models.CharField(max_length=100, verbose_name="天気名（英語）"),
        ),
        migrations.AlterField(
            model_name="jmaweathercode",
            name="summary_code",
            field=models.CharField(max_length=3, verbose_name="集計用コード"),
        ),
        migrations.AlterField(
            model_name="landblock",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="landblock",
            name="name",
            field=models.CharField(max_length=256, verbose_name="ブロック名"),
        ),
        migrations.AlterField(
            model_name="landblock",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="landblock",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="landperiod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="landperiod",
            name="name",
            field=models.CharField(max_length=256, verbose_name="時期の名前"),
        ),
        migrations.AlterField(
            model_name="landperiod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="landperiod",
            name="year",
            field=models.IntegerField(verbose_name="西暦年"),
        ),
        migrations.AlterField(
            model_name="landreview",
            name="comment",
            field=models.TextField(verbose_name="コメント"),
        ),
        migrations.AlterField(
            model_name="landreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="landreview",
            name="land_ledger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.landledger",
                verbose_name="台帳",
            ),
        ),
        migrations.AlterField(
            model_name="landreview",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="landreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="routesuggestimport",
            name="coord",
            field=models.CharField(max_length=256, verbose_name="座標文字列"),
        ),
        migrations.AlterField(
            model_name="routesuggestimport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="routesuggestimport",
            name="name",
            field=models.CharField(max_length=256, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="routesuggestimport",
            name="ordering",
            field=models.IntegerField(null=True, verbose_name="順序"),
        ),
        migrations.AlterField(
            model_name="routesuggestimport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="samplingmethod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="samplingmethod",
            name="name",
            field=models.CharField(max_length=256, verbose_name="採土法名"),
        ),
        migrations.AlterField(
            model_name="samplingmethod",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="samplingmethod",
            name="times",
            field=models.IntegerField(verbose_name="採土回数"),
        ),
        migrations.AlterField(
            model_name="samplingmethod",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="samplingorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="samplingorder",
            name="land_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.landblock",
                verbose_name="圃場ブロック",
            ),
        ),
        migrations.AlterField(
            model_name="samplingorder",
            name="ordering",
            field=models.IntegerField(verbose_name="順序"),
        ),
        migrations.AlterField(
            model_name="samplingorder",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="samplingorder",
            name="sampling_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.samplingmethod",
                verbose_name="採土法",
            ),
        ),
        migrations.AlterField(
            model_name="samplingorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurementimporterrors",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurementimporterrors",
            name="land_name",
            field=models.CharField(max_length=256, null=True, verbose_name="圃場名"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurementimporterrors",
            name="message",
            field=models.TextField(verbose_name="エラーメッセージ"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurementimporterrors",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurementimporterrors",
            name="row_number",
            field=models.IntegerField(null=True, verbose_name="行番号"),
        ),
        migrations.AlterField(
            model_name="soilchemicalmeasurementimporterrors",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="depth",
            field=models.IntegerField(verbose_name="深度(cm)"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="folder",
            field=models.CharField(max_length=256, verbose_name="フォルダ名"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="land_block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.landblock",
                verbose_name="圃場ブロック",
            ),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="land_ledger",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.landledger",
                verbose_name="台帳",
            ),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="pressure",
            field=models.IntegerField(verbose_name="圧力(kPa)"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="set_cone",
            field=models.IntegerField(verbose_name="コーン番号"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="set_datetime",
            field=models.DateTimeField(verbose_name="測定日時"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="set_depth",
            field=models.IntegerField(verbose_name="設定深度"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="set_device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="soil_analysis.device",
                verbose_name="測定デバイス",
            ),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="set_memory",
            field=models.IntegerField(verbose_name="メモリ番号"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="set_spring",
            field=models.IntegerField(verbose_name="スプリング番号"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurementimporterrors",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurementimporterrors",
            name="file",
            field=models.CharField(max_length=256, verbose_name="ファイル名"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurementimporterrors",
            name="folder",
            field=models.CharField(max_length=256, verbose_name="フォルダ名"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurementimporterrors",
            name="message",
            field=models.TextField(verbose_name="エラーメッセージ"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurementimporterrors",
            name="remark",
            field=models.TextField(null=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="soilhardnessmeasurementimporterrors",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
        ),
        migrations.AlterField(
            model_name="userattribute",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日時"),
        ),
    ]
