# Generated by Django 6.0 on 2026-05-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "soil_analysis",
            "0016_alter_company_category_alter_company_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soilchemicalmeasurement",
            name="cao_per_mgo",
        ),
        migrations.RemoveField(
            model_name="soilchemicalmeasurement",
            name="mgo_per_k2o",
        ),
        migrations.RemoveField(
            model_name="soilchemicalmeasurement",
            name="nh4_per_nitrogen",
        ),
        migrations.RemoveField(
            model_name="soilchemicalmeasurement",
            name="total_nitrogen",
        ),
    ]
