# Generated by Django 6.0 on 2026-06-01 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0017_remove_soilchemicalmeasurement_cao_per_mgo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soilchemicalmeasurement",
            name="land_ledger",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soil_chemical_measurement",
                to="soil_analysis.landledger",
                verbose_name="台帳",
            ),
        ),
    ]
