# Generated by Django 6.0 on 2026-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0018_alter_soilchemicalmeasurement_land_ledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="max_memory",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="最大メモリ数"
            ),
        ),
    ]
