# Generated by Django 6.0 on 2026-06-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0019_device_max_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="landledger",
            name="hardness_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hardness_images",
                verbose_name="硬度分布図",
            ),
        ),
    ]
