# Generated by Django 6.0 on 2026-06-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0020_landledger_hardness_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landledger",
            name="analysis_number",
        ),
        migrations.AddField(
            model_name="soilchemicalmeasurement",
            name="analysis_number",
            field=models.IntegerField(null=True, unique=True, verbose_name="分析番号"),
        ),
    ]
