# Generated by Django 6.0 on 2026-06-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0021_remove_landledger_analysis_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgriculturalRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="地域コード"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="地域名")),
                (
                    "prefecture_name",
                    models.CharField(max_length=100, verbose_name="都道府県名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EstatDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="指標キー"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "stats_data_id",
                    models.CharField(max_length=30, verbose_name="統計表ID"),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="e-Statフィルタ"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="単位"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="カテゴリ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgriculturalRiskReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="集計日")),
                (
                    "total_cultivated_area",
                    models.FloatField(null=True, verbose_name="現在の経営耕地面積"),
                ),
                (
                    "age_70_plus_area",
                    models.FloatField(null=True, verbose_name="70歳以上面積"),
                ),
                ("age_60s_area", models.FloatField(null=True, verbose_name="60代面積")),
                (
                    "no_successor_ratio",
                    models.FloatField(null=True, verbose_name="後継者なし割合"),
                ),
                (
                    "shrink_stop_intention_ratio",
                    models.FloatField(null=True, verbose_name="縮小・中止意向割合"),
                ),
                (
                    "supplemental_unmanageable_area",
                    models.FloatField(default=0, verbose_name="補助管理不能面積"),
                ),
                (
                    "aging_risk",
                    models.FloatField(null=True, verbose_name="高齢化リスク"),
                ),
                (
                    "succession_risk",
                    models.FloatField(null=True, verbose_name="継承リスク"),
                ),
                (
                    "intention_risk",
                    models.FloatField(null=True, verbose_name="意向リスク"),
                ),
                (
                    "retirement_confirmed_area",
                    models.FloatField(null=True, verbose_name="離農確定候補面積"),
                ),
                (
                    "retirement_reserve_area",
                    models.FloatField(null=True, verbose_name="離農予備軍面積"),
                ),
                (
                    "unmanageable_candidate_area",
                    models.FloatField(null=True, verbose_name="管理不能化候補面積"),
                ),
                (
                    "farmland_maintenance_rate",
                    models.FloatField(null=True, verbose_name="10年後農地維持率"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.agriculturalregion",
                        verbose_name="対象地域",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "report_date"),
                        name="agri_risk_report_region_date_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgriculturalStatisticSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_label",
                    models.CharField(max_length=50, verbose_name="対象期間"),
                ),
                ("value", models.FloatField(blank=True, null=True, verbose_name="値")),
                ("fetched_at", models.DateTimeField(verbose_name="取得日時")),
                (
                    "estat_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="e-Stat更新日時"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="e-Stat raw data"
                    ),
                ),
                (
                    "source_hash",
                    models.CharField(max_length=64, verbose_name="ソースハッシュ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.agriculturalregion",
                        verbose_name="対象地域",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soil_analysis.estatdataset",
                        verbose_name="指標定義",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at", "dataset__indicator_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("region", "dataset", "period_label", "source_hash"),
                        name="agri_snapshot_region_dataset_period_hash_unique",
                    )
                ],
            },
        ),
    ]
