# Generated by Django 6.0 on 2026-06-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil_analysis", "0022_agriculturalregion_estatdataset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplementalRiskIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="指標キー"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "source_name",
                    models.CharField(max_length=255, verbose_name="取得元"),
                ),
                ("source_url", models.URLField(verbose_name="取得元URL")),
                (
                    "region_label",
                    models.CharField(max_length=100, verbose_name="地域粒度"),
                ),
                (
                    "period_label",
                    models.CharField(max_length=100, verbose_name="対象期間"),
                ),
                ("value", models.FloatField(blank=True, null=True, verbose_name="値")),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="単位"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="カテゴリ"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "ordering": ["category", "indicator_key"],
            },
        ),
    ]
