# Generated by Django 5.1 on 2025-04-12 04:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200, verbose_name="商品コード")),
                ("name", models.CharField(max_length=200, verbose_name="商品名")),
                ("price", models.IntegerField(default=0, verbose_name="金額")),
                ("description", models.TextField(verbose_name="説明")),
                (
                    "picture",
                    models.ImageField(upload_to="shopping/", verbose_name="商品写真"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="店名")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="商品単価")),
                ("quantity", models.IntegerField(default=1, verbose_name="購入数量")),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=0.1, max_digits=5, verbose_name="税率"
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(max_length=200, verbose_name="Stripe決済ID"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "支払い待ち"),
                            ("completed", "支払い完了"),
                            ("failed", "支払い失敗"),
                            ("refunded", "返金済み"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="支払い状態",
                    ),
                ),
                (
                    "shipped",
                    models.BooleanField(default=False, verbose_name="発送済み"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="購入者",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shopping.product",
                        verbose_name="商品名",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="表示名")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="自己紹介"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shopping/staff",
                        verbose_name="プロフィール画像",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ログインユーザー",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopping.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "store"), name="unique_user_store"
                    )
                ],
            },
        ),
    ]
