# Generated by Django 6.0 on 2026-03-27 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="description",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="image",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="name",
        ),
        migrations.CreateModel(
            name="UserAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("staff", "店舗スタッフ"), ("customer", "一般購入者")],
                        max_length=20,
                        verbose_name="ロール",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="表示名"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="自己紹介"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shopping/profile",
                        verbose_name="プロフィール画像",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="住所"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="備考"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザ",
                    ),
                ),
            ],
        ),
    ]
