# Generated by Django 6.0 on 2026-03-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="staff",
            name="unique_user_store",
        ),
        migrations.AddField(
            model_name="userattribute",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_profiles",
                to="shopping.store",
                verbose_name="所属店舗",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
