# Generated by Django 6.0 on 2026-06-28 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shopping",
            "0004_remove_customer_user_remove_staff_unique_user_store_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePlanningDataSourceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="データソースキー"
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="表示名"),
                ),
                (
                    "source_url",
                    models.URLField(max_length=500, verbose_name="提供元URL"),
                ),
                ("status", models.CharField(max_length=100, verbose_name="取得状態")),
                (
                    "data_period",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="データ時点"
                    ),
                ),
                (
                    "source_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提供元更新日時"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="アプリ取得日時"
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="取得メタデータ"
                    ),
                ),
            ],
        ),
    ]
