# Generated by Django 6.0 on 2026-06-30 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0005_storeplanningdatasourcesnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePlanningTargetStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="店舗キー"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="店舗名")),
                ("address", models.CharField(max_length=500, verbose_name="住所")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="緯度"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="経度"),
                ),
                (
                    "city_code",
                    models.CharField(
                        max_length=10, verbose_name="e-Stat市区町村コード"
                    ),
                ),
                (
                    "town_code",
                    models.CharField(max_length=10, verbose_name="e-Stat町丁字コード"),
                ),
                (
                    "population_area",
                    models.CharField(max_length=255, verbose_name="人口集計地域"),
                ),
                (
                    "large_area_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="大字・町名"
                    ),
                ),
                (
                    "small_area_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="字・丁目名"
                    ),
                ),
                (
                    "area_hierarchy_level",
                    models.CharField(
                        default="4", max_length=1, verbose_name="地域階層レベル"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="表示対象"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
