# Generated by Django 6.0 on 2026-07-01 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0011_label_sapporo_clock_tower_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePlanningGoogleMapsReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(max_length=200, verbose_name="Google Place ID"),
                ),
                (
                    "target_store_slug",
                    models.SlugField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="店舗キー",
                    ),
                ),
                ("place_name", models.CharField(max_length=255, verbose_name="施設名")),
                ("latitude", models.FloatField(verbose_name="緯度")),
                ("longitude", models.FloatField(verbose_name="経度")),
                (
                    "rating",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Google Maps rating"
                    ),
                ),
                (
                    "review_text",
                    models.TextField(blank=True, verbose_name="レビュー本文"),
                ),
                (
                    "author",
                    models.CharField(blank=True, max_length=200, verbose_name="投稿者"),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="レビュー公開日時"
                    ),
                ),
                (
                    "google_maps_uri",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Google Maps URL"
                    ),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="アプリ取得日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "target_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_maps_reviews",
                        to="shopping.storeplanningtargetstore",
                        verbose_name="出店計画対象店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["-publish_time", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_store_slug", "google_place_id", "author"),
                        name="unique_store_planning_google_review_author",
                    )
                ],
            },
        ),
    ]
