# Generated by Django 6.0 on 2026-07-02 09:09

from django.db import migrations, models


def set_store_planning_business_types(apps, schema_editor):
    StorePlanningTargetStore = apps.get_model("shopping", "StorePlanningTargetStore")
    store_business_types = {
        "chapter-table": {
            "business_type_label": "カフェ",
            "business_search_query": "カフェ",
        },
        "okei-taproom": {
            "business_type_label": "クラフトビール",
            "business_search_query": "クラフトビール",
        },
        "sapporo-clock-tower": {
            "business_type_label": "観光施設",
            "business_search_query": "観光スポット",
        },
    }
    for slug, values in store_business_types.items():
        StorePlanningTargetStore.objects.filter(slug=slug).update(**values)


def restore_store_planning_business_types(apps, schema_editor):
    StorePlanningTargetStore = apps.get_model("shopping", "StorePlanningTargetStore")
    StorePlanningTargetStore.objects.update(
        business_type_label="飲食店",
        business_search_query="レストラン",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0012_storeplanninggooglemapsreview"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storeplanninggooglemapsreview",
            name="unique_store_planning_google_review_author",
        ),
        migrations.AddField(
            model_name="storeplanninggooglemapsreview",
            name="review_scope",
            field=models.CharField(
                choices=[
                    ("target_store", "対象店舗"),
                    ("nearby_same_business", "周辺同業店舗"),
                ],
                db_index=True,
                default="target_store",
                max_length=50,
                verbose_name="レビュー種別",
            ),
        ),
        migrations.AddField(
            model_name="storeplanningtargetstore",
            name="business_search_query",
            field=models.CharField(
                default="レストラン", max_length=255, verbose_name="同業検索語"
            ),
        ),
        migrations.AddField(
            model_name="storeplanningtargetstore",
            name="business_type_label",
            field=models.CharField(
                default="飲食店", max_length=100, verbose_name="業態"
            ),
        ),
        migrations.RunPython(
            set_store_planning_business_types,
            restore_store_planning_business_types,
        ),
        migrations.AddConstraint(
            model_name="storeplanninggooglemapsreview",
            constraint=models.UniqueConstraint(
                fields=(
                    "target_store_slug",
                    "review_scope",
                    "google_place_id",
                    "author",
                ),
                name="unique_store_planning_google_review_scope_author",
            ),
        ),
    ]
