# Generated by Django 6.0 on 2026-07-02 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shopping",
            "0013_remove_storeplanninggooglemapsreview_unique_store_planning_google_review_author_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePlanningGoogleMapsReviewAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "ポジティブ"),
                            ("negative", "ネガティブ"),
                            ("neutral", "中立"),
                        ],
                        db_index=True,
                        default="neutral",
                        max_length=20,
                        verbose_name="感情分類",
                    ),
                ),
                (
                    "sentiment_score",
                    models.IntegerField(default=0, verbose_name="感情スコア"),
                ),
                (
                    "one_line_summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="1行要約"
                    ),
                ),
                (
                    "issue",
                    models.CharField(blank=True, max_length=255, verbose_name="課題点"),
                ),
                (
                    "location_insight",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="立地示唆"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="LLMモデル名"),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        max_length=50, verbose_name="プロンプトバージョン"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(blank=True, default=dict, verbose_name="LLM応答"),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="分析日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="shopping.storeplanninggooglemapsreview",
                        verbose_name="Google Mapsレビュー",
                    ),
                ),
            ],
            options={
                "ordering": ["review__place_name", "-analyzed_at"],
            },
        ),
    ]
