# Generated by Django 6.0 on 2026-07-02 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0014_storeplanninggooglemapsreviewanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePlanningGoogleMapsPlaceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_store_slug",
                    models.SlugField(
                        blank=True, max_length=100, verbose_name="店舗キー"
                    ),
                ),
                (
                    "review_scope",
                    models.CharField(
                        choices=[
                            ("target_store", "対象店舗"),
                            ("nearby_same_business", "周辺同業店舗"),
                        ],
                        db_index=True,
                        default="target_store",
                        max_length=50,
                        verbose_name="レビュー種別",
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(max_length=200, verbose_name="Google Place ID"),
                ),
                ("place_name", models.CharField(max_length=255, verbose_name="施設名")),
                (
                    "rating",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Google Maps rating"
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="保存レビュー数"
                    ),
                ),
                (
                    "positive_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ポジティブ要因数"
                    ),
                ),
                (
                    "negative_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ネガティブ要因数"
                    ),
                ),
                (
                    "sentiment_score",
                    models.IntegerField(default=0, verbose_name="評判スコア"),
                ),
                (
                    "one_line_summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="1行要約"
                    ),
                ),
                (
                    "issue",
                    models.CharField(blank=True, max_length=255, verbose_name="課題点"),
                ),
                (
                    "location_insight",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="立地示唆"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="LLMモデル名"),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        max_length=50, verbose_name="プロンプトバージョン"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(blank=True, default=dict, verbose_name="LLM応答"),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="分析日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                (
                    "target_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_maps_place_summaries",
                        to="shopping.storeplanningtargetstore",
                        verbose_name="出店計画対象店舗",
                    ),
                ),
            ],
            options={
                "ordering": ["review_scope", "place_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_store_slug", "review_scope", "google_place_id"),
                        name="unique_store_planning_google_place_summary",
                    )
                ],
            },
        ),
    ]
